/**
 * Generates a seed SQL migration for one Question Library tranche.
 *
 *   npx vite-node scripts/generate-careerprep-migration.ts -- tranche1 20260704093000
 *
 * Inserts are guarded with WHERE NOT EXISTS on slug, so re-running a
 * migration (or overlapping tranches) can never duplicate questions.
 * Mission children resolve parent_id from their root's slug at insert time.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { datasets } from "../supabase/seed/careerprep/datasets";
import type { SeedQuestion } from "../supabase/seed/careerprep/types";

const [trancheName, stamp] = process.argv.slice(2).filter((a) => a !== "--");
if (!trancheName || !stamp) {
  console.error("usage: vite-node scripts/generate-careerprep-migration.ts -- <trancheN> <YYYYMMDDHHMMSS>");
  process.exit(1);
}

const mod = await import(`../supabase/seed/careerprep/${trancheName}.ts`);
const questions: SeedQuestion[] = mod[trancheName];
if (!Array.isArray(questions)) throw new Error(`No export "${trancheName}" in ${trancheName}.ts`);

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const qj = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const qarr = (a: string[]) => (a.length ? `ARRAY[${a.map(q).join(",")}]::text[]` : "ARRAY[]::text[]");

const statements: string[] = [];

// Emit each referenced dataset once into a temp table; question rows join it
// by name, keeping the migration ~5x smaller than inlining per row.
const usedDatasets = [...new Set(questions.map((s) => s.dataset).filter(Boolean))] as string[];
for (const d of usedDatasets) if (!datasets[d]) throw new Error(`Unknown dataset ${d}`);
statements.push(`CREATE TEMP TABLE _worlds (name text PRIMARY KEY, schema_sql text, initial_sql text);`);
statements.push(
  `INSERT INTO _worlds VALUES\n` +
    usedDatasets.map((d) => `  (${q(d)}, ${q(datasets[d].schema_sql)}, ${q(datasets[d].initial_sql)})`).join(",\n") +
    ";",
);

// Roots first so children can resolve parent_id by slug.
const ordered = [...questions].sort((a, b) => Number(Boolean(a.parent_slug)) - Number(Boolean(b.parent_slug)));

for (const s of ordered) {
  const parentExpr = s.parent_slug
    ? `(SELECT id FROM public.careerprep_questions WHERE slug = ${q(s.parent_slug)})`
    : "NULL";
  const worldSel = (col: string) =>
    s.dataset ? `COALESCE((SELECT ${col} FROM _worlds WHERE name = ${q(s.dataset)}), '')` : "''";
  statements.push(`INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT ${q(s.slug)}, ${q(s.title)}, ${q(s.question_type)}, ${q(s.difficulty)}, ${q(s.industry)},
       ${q(s.category)}, ${qarr(s.tags ?? [])}, ${q(s.content_md)},
       ${worldSel("schema_sql")}, ${worldSel("initial_sql")}, ${q(s.solution_sql ?? "")},
       ${qj(s.hints ?? [])}, ${qj(s.options ?? [])}, ${s.correct_option ? q(s.correct_option) : "NULL"},
       ${parentExpr}, ${s.order_index ?? 0}, ${s.time_limit_secs ?? "NULL"}, ${s.success_rate ?? 50}
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = ${q(s.slug)});`);
}

statements.push("DROP TABLE _worlds;");

const sql = `-- Question Library seed: ${trancheName} (${questions.length} questions).
-- Generated by scripts/generate-careerprep-migration.ts from supabase/seed/careerprep/${trancheName}.ts
-- Idempotent: each insert is guarded by slug.

${statements.join("\n\n")}
`;

const out = resolve(`supabase/migrations/${stamp}_seed_careerprep_${trancheName}.sql`);
writeFileSync(out, sql);
console.log(`${questions.length} questions → ${out} (${(sql.length / 1024).toFixed(0)} KB)`);
