-- Question Library seed: tranche3 (76 questions).
-- Generated by scripts/generate-careerprep-migration.ts from supabase/seed/careerprep/tranche3.ts
-- Idempotent: each insert is guarded by slug.

CREATE TEMP TABLE _worlds (name text PRIMARY KEY, schema_sql text, initial_sql text);

INSERT INTO _worlds VALUES
  ('fintech_wallet', 'CREATE TABLE users (
  user_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  district TEXT NOT NULL,
  joined_at DATE NOT NULL,
  kyc_verified BOOLEAN NOT NULL
);
CREATE TABLE agents (
  agent_id INT PRIMARY KEY,
  shop_name TEXT NOT NULL,
  district TEXT NOT NULL
);
CREATE TABLE transactions (
  txn_id INT PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(user_id),
  agent_id INT REFERENCES agents(agent_id),
  txn_type TEXT NOT NULL, -- ''cash_in'' | ''cash_out'' | ''send_money'' | ''payment''
  amount NUMERIC(12,2) NOT NULL,
  fee NUMERIC(10,2) NOT NULL DEFAULT 0,
  txn_at TIMESTAMP NOT NULL,
  status TEXT NOT NULL -- ''success'' | ''failed'' | ''reversed''
);', 'INSERT INTO users VALUES
  (1,''Rahim Uddin'',''Dhaka'',''2025-11-03'',true),
  (2,''Karima Akter'',''Chattogram'',''2025-12-18'',true),
  (3,''Sabbir Hossain'',''Dhaka'',''2026-01-25'',false),
  (4,''Nusrat Jahan'',''Sylhet'',''2026-02-07'',true),
  (5,''Tanvir Ahmed'',''Khulna'',''2026-02-19'',true),
  (6,''Mim Chowdhury'',''Dhaka'',''2026-03-12'',false),
  (7,''Arif Islam'',''Rajshahi'',''2026-04-02'',true),
  (8,''Farzana Haque'',''Chattogram'',''2026-04-28'',true);
INSERT INTO agents VALUES
  (101,''Bhai Bhai Telecom'',''Dhaka''),
  (102,''Ma Enterprise'',''Chattogram''),
  (103,''Padma Store'',''Rajshahi''),
  (104,''Digital Point'',''Dhaka'');
INSERT INTO transactions VALUES
  (1001,1,101,''cash_in'',5000.00,0,''2026-06-01 09:15:00'',''success''),
  (1002,1,NULL,''send_money'',1200.00,5.00,''2026-06-01 12:40:00'',''success''),
  (1003,2,102,''cash_in'',8000.00,0,''2026-06-02 10:05:00'',''success''),
  (1004,2,102,''cash_out'',3000.00,55.50,''2026-06-03 16:22:00'',''success''),
  (1005,3,101,''cash_in'',2000.00,0,''2026-06-03 18:30:00'',''success''),
  (1006,3,NULL,''payment'',450.00,0,''2026-06-04 11:00:00'',''success''),
  (1007,4,NULL,''send_money'',2500.00,10.00,''2026-06-04 14:45:00'',''failed''),
  (1008,4,NULL,''send_money'',2500.00,10.00,''2026-06-04 14:52:00'',''success''),
  (1009,5,104,''cash_in'',12000.00,0,''2026-06-05 09:00:00'',''success''),
  (1010,5,104,''cash_out'',7000.00,129.50,''2026-06-05 19:10:00'',''success''),
  (1011,1,NULL,''payment'',890.00,0,''2026-06-06 08:20:00'',''success''),
  (1012,6,101,''cash_in'',1500.00,0,''2026-06-06 13:33:00'',''success''),
  (1013,6,NULL,''send_money'',700.00,5.00,''2026-06-07 10:11:00'',''reversed''),
  (1014,7,103,''cash_in'',6000.00,0,''2026-06-07 15:55:00'',''success''),
  (1015,7,103,''cash_out'',2000.00,37.00,''2026-06-08 09:47:00'',''success''),
  (1016,8,102,''cash_in'',9500.00,0,''2026-06-08 11:28:00'',''success''),
  (1017,8,NULL,''payment'',1250.00,0,''2026-06-09 17:05:00'',''success''),
  (1018,2,NULL,''send_money'',4000.00,10.00,''2026-06-10 12:00:00'',''success''),
  (1019,5,NULL,''payment'',3200.00,0,''2026-06-10 20:15:00'',''success''),
  (1020,1,101,''cash_out'',2500.00,46.25,''2026-06-11 10:30:00'',''success''),
  (1021,4,102,''cash_in'',3000.00,0,''2026-06-11 14:00:00'',''success''),
  (1022,7,NULL,''send_money'',900.00,5.00,''2026-06-12 09:05:00'',''success''),
  (1023,8,102,''cash_out'',5000.00,92.50,''2026-06-12 18:40:00'',''failed''),
  (1024,8,102,''cash_out'',5000.00,92.50,''2026-06-12 18:47:00'',''success'');'),
  ('fintech_microloan', 'CREATE TABLE loans (
  loan_id INT PRIMARY KEY,
  borrower TEXT NOT NULL,
  district TEXT NOT NULL,
  principal NUMERIC(12,2) NOT NULL,
  disbursed_on DATE NOT NULL,
  term_months INT NOT NULL,
  status TEXT NOT NULL -- ''active'' | ''paid'' | ''defaulted''
);
CREATE TABLE repayments (
  repayment_id INT PRIMARY KEY,
  loan_id INT NOT NULL REFERENCES loans(loan_id),
  amount NUMERIC(10,2) NOT NULL,
  paid_on DATE NOT NULL
);', 'INSERT INTO loans VALUES
  (201,''Hasan Mahmud'',''Dhaka'',20000.00,''2026-01-10'',6,''active''),
  (202,''Ruma Begum'',''Chattogram'',15000.00,''2026-01-22'',6,''paid''),
  (203,''Sohel Rana'',''Dhaka'',30000.00,''2026-02-05'',12,''active''),
  (204,''Moriom Akter'',''Sylhet'',10000.00,''2026-02-18'',3,''paid''),
  (205,''Rasel Mia'',''Rajshahi'',25000.00,''2026-03-02'',12,''defaulted''),
  (206,''Shirin Sultana'',''Dhaka'',12000.00,''2026-03-15'',6,''active''),
  (207,''Jamal Uddin'',''Khulna'',18000.00,''2026-04-01'',6,''active''),
  (208,''Taslima Khatun'',''Chattogram'',8000.00,''2026-04-20'',3,''paid'');
INSERT INTO repayments VALUES
  (301,201,3500.00,''2026-02-10''),(302,201,3500.00,''2026-03-10''),
  (303,201,3500.00,''2026-04-12''),(304,202,2650.00,''2026-02-22''),
  (305,202,2650.00,''2026-03-20''),(306,202,2650.00,''2026-04-21''),
  (307,202,2650.00,''2026-05-19''),(308,202,2650.00,''2026-06-18''),
  (309,203,2800.00,''2026-03-05''),(310,203,2800.00,''2026-04-07''),
  (311,204,3450.00,''2026-03-18''),(312,204,3450.00,''2026-04-16''),
  (313,204,3450.00,''2026-05-18''),(314,205,2300.00,''2026-04-02''),
  (315,206,2150.00,''2026-04-15''),(316,206,2150.00,''2026-05-16''),
  (317,207,3200.00,''2026-05-01''),(318,207,3200.00,''2026-06-02''),
  (319,208,2750.00,''2026-05-20''),(320,208,2750.00,''2026-06-19'');'),
  ('ecommerce_shop', 'CREATE TABLE customers (
  customer_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  signup_date DATE NOT NULL
);
CREATE TABLE products (
  product_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC(10,2) NOT NULL
);
CREATE TABLE orders (
  order_id INT PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customers(customer_id),
  order_date DATE NOT NULL,
  status TEXT NOT NULL -- ''delivered'' | ''cancelled'' | ''returned'' | ''processing''
);
CREATE TABLE order_items (
  order_id INT NOT NULL REFERENCES orders(order_id),
  product_id INT NOT NULL REFERENCES products(product_id),
  quantity INT NOT NULL,
  unit_price NUMERIC(10,2) NOT NULL,
  PRIMARY KEY (order_id, product_id)
);', 'INSERT INTO customers VALUES
  (1,''Shorna Rahman'',''Dhaka'',''2025-10-11''),
  (2,''Imran Kabir'',''Chattogram'',''2025-12-02''),
  (3,''Priya Das'',''Dhaka'',''2026-01-15''),
  (4,''Rakib Hasan'',''Sylhet'',''2026-02-20''),
  (5,''Lamia Islam'',''Khulna'',''2026-03-08''),
  (6,''Fahim Chowdhury'',''Dhaka'',''2026-04-19'');
INSERT INTO products VALUES
  (11,''Wireless Earbuds'',''Electronics'',2490.00),
  (12,''Cotton Panjabi'',''Fashion'',1850.00),
  (13,''Blender 500W'',''Home Appliance'',3200.00),
  (14,''Yoga Mat'',''Sports'',990.00),
  (15,''Power Bank 20000mAh'',''Electronics'',1750.00),
  (16,''Deshi Cotton Saree'',''Fashion'',2950.00),
  (17,''LED Desk Lamp'',''Home Appliance'',780.00),
  (18,''Gaming Mouse'',''Electronics'',1450.00);
INSERT INTO orders VALUES
  (501,1,''2026-05-02'',''delivered''),
  (502,2,''2026-05-04'',''delivered''),
  (503,1,''2026-05-10'',''returned''),
  (504,3,''2026-05-12'',''delivered''),
  (505,4,''2026-05-15'',''cancelled''),
  (506,5,''2026-05-18'',''delivered''),
  (507,3,''2026-05-21'',''delivered''),
  (508,6,''2026-05-25'',''processing''),
  (509,2,''2026-06-01'',''delivered''),
  (510,1,''2026-06-05'',''delivered'');
INSERT INTO order_items VALUES
  (501,11,1,2490.00),(501,14,2,990.00),
  (502,12,1,1850.00),
  (503,13,1,3200.00),
  (504,15,2,1750.00),(504,17,1,780.00),
  (505,16,1,2950.00),
  (506,11,1,2490.00),(506,15,1,1750.00),
  (507,14,1,990.00),(507,17,2,780.00),
  (508,13,1,3200.00),
  (509,16,2,2950.00),(509,12,1,1850.00),
  (510,15,1,1600.00);'),
  ('logistics_courier', 'CREATE TABLE hubs (
  hub_id INT PRIMARY KEY,
  city TEXT NOT NULL
);
CREATE TABLE riders (
  rider_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  hub_id INT NOT NULL REFERENCES hubs(hub_id)
);
CREATE TABLE parcels (
  parcel_id INT PRIMARY KEY,
  sender_area TEXT NOT NULL,
  receiver_area TEXT NOT NULL,
  weight_kg NUMERIC(6,2) NOT NULL,
  cod_amount NUMERIC(10,2) NOT NULL, -- cash on delivery, 0 = prepaid
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE deliveries (
  delivery_id INT PRIMARY KEY,
  parcel_id INT NOT NULL REFERENCES parcels(parcel_id),
  rider_id INT NOT NULL REFERENCES riders(rider_id),
  picked_at TIMESTAMP NOT NULL,
  delivered_at TIMESTAMP, -- NULL = not delivered yet
  status TEXT NOT NULL -- ''delivered'' | ''in_transit'' | ''failed''
);', 'INSERT INTO hubs VALUES (1,''Dhaka''),(2,''Chattogram''),(3,''Sylhet'');
INSERT INTO riders VALUES
  (21,''Jashim Uddin'',1),(22,''Selim Reza'',1),(23,''Polash Mia'',2),
  (24,''Hridoy Khan'',2),(25,''Shuvo Roy'',3);
INSERT INTO parcels VALUES
  (301,''Uttara'',''Dhanmondi'',1.20,1500.00,''2026-06-01 08:00:00''),
  (302,''Banani'',''Mirpur'',0.50,0,''2026-06-01 09:30:00''),
  (303,''Agrabad'',''Nasirabad'',2.80,3200.00,''2026-06-01 10:15:00''),
  (304,''Gulshan'',''Uttara'',0.90,850.00,''2026-06-02 08:45:00''),
  (305,''Zindabazar'',''Ambarkhana'',1.50,2100.00,''2026-06-02 11:20:00''),
  (306,''Dhanmondi'',''Banani'',3.40,0,''2026-06-03 09:00:00''),
  (307,''Mirpur'',''Gulshan'',0.75,650.00,''2026-06-03 14:30:00''),
  (308,''Nasirabad'',''Agrabad'',1.10,1200.00,''2026-06-04 10:00:00''),
  (309,''Uttara'',''Mirpur'',2.00,1800.00,''2026-06-04 15:45:00''),
  (310,''Ambarkhana'',''Zindabazar'',0.60,0,''2026-06-05 09:10:00'');
INSERT INTO deliveries VALUES
  (401,301,21,''2026-06-01 10:00:00'',''2026-06-01 15:30:00'',''delivered''),
  (402,302,22,''2026-06-01 11:00:00'',''2026-06-01 13:45:00'',''delivered''),
  (403,303,23,''2026-06-01 12:30:00'',''2026-06-02 17:00:00'',''delivered''),
  (404,304,21,''2026-06-02 10:30:00'',''2026-06-02 14:20:00'',''delivered''),
  (405,305,25,''2026-06-02 13:00:00'',NULL,''in_transit''),
  (406,306,22,''2026-06-03 11:00:00'',''2026-06-04 10:30:00'',''delivered''),
  (407,307,21,''2026-06-03 16:00:00'',NULL,''failed''),
  (408,307,22,''2026-06-04 09:00:00'',''2026-06-04 12:15:00'',''delivered''),
  (409,308,24,''2026-06-04 11:30:00'',''2026-06-04 18:40:00'',''delivered''),
  (410,309,21,''2026-06-05 08:30:00'',NULL,''in_transit''),
  (411,310,25,''2026-06-05 10:00:00'',''2026-06-05 12:00:00'',''delivered'');'),
  ('telco_network', 'CREATE TABLE plans (
  plan_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  monthly_fee NUMERIC(8,2) NOT NULL,
  data_gb INT NOT NULL
);
CREATE TABLE subscribers (
  sub_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  plan_id INT NOT NULL REFERENCES plans(plan_id),
  activated_on DATE NOT NULL,
  district TEXT NOT NULL
);
CREATE TABLE recharges (
  recharge_id INT PRIMARY KEY,
  sub_id INT NOT NULL REFERENCES subscribers(sub_id),
  amount NUMERIC(8,2) NOT NULL,
  recharged_at TIMESTAMP NOT NULL
);
CREATE TABLE usage_daily (
  sub_id INT NOT NULL REFERENCES subscribers(sub_id),
  usage_date DATE NOT NULL,
  data_mb INT NOT NULL,
  voice_min INT NOT NULL,
  PRIMARY KEY (sub_id, usage_date)
);', 'INSERT INTO plans VALUES
  (1,''Bondhu 199'',199.00,5),(2,''Shadhin 349'',349.00,15),
  (3,''Power 599'',599.00,40),(4,''Business 999'',999.00,100);
INSERT INTO subscribers VALUES
  (61,''Mahmud Hasan'',1,''2025-09-14'',''Dhaka''),
  (62,''Rima Sultana'',2,''2025-11-30'',''Chattogram''),
  (63,''Joy Barua'',2,''2026-01-08'',''Chattogram''),
  (64,''Sadia Afrin'',3,''2026-02-14'',''Dhaka''),
  (65,''Nayeem Islam'',1,''2026-03-22'',''Rajshahi''),
  (66,''Tania Akter'',4,''2026-04-05'',''Dhaka'');
INSERT INTO recharges VALUES
  (901,61,199.00,''2026-06-01 08:00:00''),
  (902,62,349.00,''2026-06-01 09:30:00''),
  (903,63,100.00,''2026-06-02 12:00:00''),
  (904,63,249.00,''2026-06-03 10:15:00''),
  (905,64,599.00,''2026-06-03 18:20:00''),
  (906,65,199.00,''2026-06-04 11:00:00''),
  (907,66,999.00,''2026-06-05 09:45:00''),
  (908,61,50.00,''2026-06-08 20:30:00''),
  (909,62,100.00,''2026-06-10 14:10:00'');
INSERT INTO usage_daily VALUES
  (61,''2026-06-01'',350,22),(61,''2026-06-02'',420,15),(61,''2026-06-03'',180,40),
  (62,''2026-06-01'',900,10),(62,''2026-06-02'',1150,8),(62,''2026-06-03'',600,25),
  (63,''2026-06-01'',450,30),(63,''2026-06-02'',380,45),(63,''2026-06-03'',720,12),
  (64,''2026-06-01'',2100,5),(64,''2026-06-02'',1800,18),(64,''2026-06-03'',2500,7),
  (65,''2026-06-01'',120,60),(65,''2026-06-02'',90,75),(65,''2026-06-03'',200,55),
  (66,''2026-06-01'',3400,20),(66,''2026-06-02'',4100,35),(66,''2026-06-03'',2900,28);');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'users-joined-2026', 'The 2026 Cohort', 'code', 'Easy', 'Fintech',
       'Filtering', ARRAY['where','date']::text[], 'Growth reviews this year''s signups. Return `name` and `joined_at` of users who joined in 2026, earliest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT name, joined_at FROM users WHERE joined_at >= ''2026-01-01'' ORDER BY joined_at;',
       '["A simple date lower bound","Earliest first = ascending order"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 88
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'users-joined-2026');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'name-search-islam', 'Directory Search', 'code', 'Easy', 'Fintech',
       'String Functions', ARRAY['like']::text[], 'Support''s directory search: return `user_id` and `name` of users whose name contains **"Islam"**, by user_id.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT user_id, name FROM users WHERE name LIKE ''%Islam%'' ORDER BY user_id;',
       '["LIKE with % wildcards on both sides","Case matters with LIKE; the data capitalises Islam"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 84
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'name-search-islam');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'reversed-transactions-log', 'Reversal Audit Log', 'code', 'Easy', 'Fintech',
       'Joins', ARRAY['join','where']::text[], 'Every reversal is audited. Return `txn_id`, user `name`, `amount`, and `txn_at` of reversed transactions, newest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT t.txn_id, u.name, t.amount, t.txn_at
FROM transactions t JOIN users u ON u.user_id = t.user_id
WHERE t.status = ''reversed'' ORDER BY t.txn_at DESC;',
       '["Join for the name, filter status = ''reversed''","Newest first = ORDER BY txn_at DESC"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 80
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'reversed-transactions-log');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'district-user-counts', 'Users per District', 'code', 'Easy', 'Fintech',
       'Aggregation', ARRAY['group-by','count']::text[], 'Return each `district` and its user count (`users_count`), largest first, ties alphabetical.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT district, COUNT(*) AS users_count FROM users GROUP BY district ORDER BY users_count DESC, district;',
       '["GROUP BY district","Two-level ORDER BY for stable ties"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 86
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'district-user-counts');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'weekend-transactions', 'Weekend Transaction Volume', 'code', 'Medium', 'Fintech',
       'Date Functions', ARRAY['extract','dow']::text[], 'Do weekends behave differently? Return total successful volume (`weekend_volume`) for transactions on Saturdays and Sundays — one row. (June 6/7, 13/14... 2026 are weekend dates in the data.)',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT SUM(amount) AS weekend_volume
FROM transactions
WHERE status = ''success'' AND EXTRACT(DOW FROM txn_at) IN (0, 6);',
       '["EXTRACT(DOW FROM ts): 0 = Sunday, 6 = Saturday","One aggregate row — no GROUP BY"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 55
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'weekend-transactions');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'fee-free-users', 'Users Who Never Paid a Fee', 'code', 'Medium', 'Fintech',
       'Aggregation', ARRAY['having','sum']::text[], 'Pricing wonders who rides free. Return `user_id` and `name` of users whose successful transactions carried **zero total fees**, by user_id.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.user_id, u.name
FROM users u JOIN transactions t ON t.user_id = u.user_id
WHERE t.status = ''success''
GROUP BY u.user_id, u.name
HAVING SUM(t.fee) = 0
ORDER BY u.user_id;',
       '["SUM(fee) per user","HAVING SUM(fee) = 0 — the test is on an aggregate"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 58
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'fee-free-users');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'agent-vs-app-mix', 'Agent vs App Split', 'code', 'Medium', 'Fintech',
       'Conditional Aggregation', ARRAY['case-when','null']::text[], 'One row for the channel report: count of successful **agent-assisted** transactions (`agent_txns`) and **app-only** transactions (`app_txns`).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT
  COUNT(*) FILTER (WHERE agent_id IS NOT NULL) AS agent_txns,
  COUNT(*) FILTER (WHERE agent_id IS NULL) AS app_txns
FROM transactions WHERE status = ''success'';',
       '["agent_id NULL-ness is the channel","COUNT(*) FILTER (WHERE ...) or SUM(CASE...)"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 60
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'agent-vs-app-mix');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'days-since-last-txn', 'Dormancy Snapshot', 'code', 'Medium', 'Fintech',
       'Date Arithmetic', ARRAY['max','date-diff']::text[], 'As of **2026-06-15**, how stale is each user? Return `name`, last transaction date (`last_txn`), and `days_quiet` (days from last_txn to 2026-06-15), most dormant first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.name, MAX(t.txn_at)::date AS last_txn,
       DATE ''2026-06-15'' - MAX(t.txn_at)::date AS days_quiet
FROM users u JOIN transactions t ON t.user_id = u.user_id
GROUP BY u.name ORDER BY days_quiet DESC;',
       '["MAX(txn_at) per user, cast to date","date - date = integer days"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 56
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'days-since-last-txn');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'above-average-fees', 'Above-Average Fee Payers', 'code', 'Medium', 'Fintech',
       'Subqueries', ARRAY['scalar-subquery','having']::text[], 'Return `user_id` and total fees paid (`fees_paid`) of users who paid **more total fees than the average user''s total**, highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT user_id, SUM(fee) AS fees_paid
FROM transactions WHERE status = ''success''
GROUP BY user_id
HAVING SUM(fee) > (
  SELECT AVG(user_total) FROM (
    SELECT SUM(fee) AS user_total FROM transactions WHERE status = ''success'' GROUP BY user_id
  ) t
)
ORDER BY fees_paid DESC;',
       '["Average-of-user-totals needs a nested aggregate","Compare in HAVING against the scalar subquery"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 44
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'above-average-fees');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'loan-term-buckets', 'Loan Term Buckets', 'code', 'Medium', 'Fintech',
       'Conditional Aggregation', ARRAY['case-when','bucketing']::text[], 'Bucket the loan book: `''short''` (≤ 3 months), `''standard''` (4–6), `''long''` (> 6). Return `term_bucket`, `loans`, and `principal_total`, largest principal first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT CASE WHEN term_months <= 3 THEN ''short''
            WHEN term_months <= 6 THEN ''standard''
            ELSE ''long'' END AS term_bucket,
       COUNT(*) AS loans, SUM(principal) AS principal_total
FROM loans GROUP BY 1 ORDER BY principal_total DESC;',
       '["CASE builds the bucket label","GROUP BY 1 groups by that expression"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 59
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'loan-term-buckets');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'biggest-single-repayment', 'Largest Repayment per District', 'code', 'Hard', 'Fintech',
       'Window Functions', ARRAY['row-number','join']::text[], 'Per district, the single largest repayment ever received: return `district`, `borrower`, `amount`, and `paid_on`, largest amount first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT district, borrower, amount, paid_on FROM (
  SELECT l.district, l.borrower, r.amount, r.paid_on,
         ROW_NUMBER() OVER (PARTITION BY l.district ORDER BY r.amount DESC, r.paid_on) AS rn
  FROM loans l JOIN repayments r ON r.loan_id = l.loan_id
) t WHERE rn = 1 ORDER BY amount DESC;',
       '["Partition by district, order by amount descending","Tie-break inside the window","Keep rn = 1"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 37
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'biggest-single-repayment');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'repayment-month-over-month', 'Collections Month-over-Month', 'code', 'Hard', 'Fintech',
       'Window Functions', ARRAY['lag','date-trunc']::text[], 'Finance wants the trend with deltas. Per month, return `month`, `collected`, and `vs_prev_month` (difference from the previous month, NULL for the first), chronological.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT month, collected, collected - LAG(collected) OVER (ORDER BY month) AS vs_prev_month
FROM (
  SELECT DATE_TRUNC(''month'', paid_on)::date AS month, SUM(amount) AS collected
  FROM repayments GROUP BY 1
) m ORDER BY month;',
       '["Aggregate per month first","LAG over the month order gives the previous value"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 35
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'repayment-month-over-month');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'kyc-volume-comparison', 'KYC vs Non-KYC Volume', 'code', 'Hard', 'Fintech',
       'Conditional Aggregation', ARRAY['case-when','ratio']::text[], 'Regulators ask: how much successful volume flows through **unverified** users? Return one row: `verified_volume`, `unverified_volume`, and `unverified_pct` of the total (1 decimal).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT
  SUM(CASE WHEN u.kyc_verified THEN t.amount ELSE 0 END) AS verified_volume,
  SUM(CASE WHEN NOT u.kyc_verified THEN t.amount ELSE 0 END) AS unverified_volume,
  ROUND(100.0 * SUM(CASE WHEN NOT u.kyc_verified THEN t.amount ELSE 0 END) / SUM(t.amount), 1) AS unverified_pct
FROM users u JOIN transactions t ON t.user_id = u.user_id
WHERE t.status = ''success'';',
       '["Split the SUM with CASE on kyc_verified","The percentage reuses the same conditional sums"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 39
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'kyc-volume-comparison');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-exists-vs-in', 'EXISTS vs IN', 'mcq', 'Medium', 'Fintech',
       'Subqueries', ARRAY['concept']::text[], 'Both `WHERE user_id IN (SELECT ...)` and `WHERE EXISTS (SELECT 1 ...)` can express "users with transactions".

Which statement is TRUE?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"EXISTS checks for the existence of matching rows and can short-circuit; IN materialises the value list"},{"label":"B","text":"IN is always faster"},{"label":"C","text":"EXISTS cannot use a correlated subquery"},{"label":"D","text":"They can never return the same result"}]'::jsonb, 'A',
       NULL, 0, NULL, 57
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-exists-vs-in');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-round-two-args', 'ROUND With Two Arguments', 'mcq', 'Easy', 'Fintech',
       'Numeric Functions', ARRAY['round']::text[], '`SELECT ROUND(123.4567, 2);`

What comes back?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"123.46"},{"label":"B","text":"123.45"},{"label":"C","text":"123"},{"label":"D","text":"120"}]'::jsonb, 'A',
       NULL, 0, NULL, 85
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-round-two-args');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-order-of-execution', 'Logical Order of a Query', 'mcq', 'Medium', 'Fintech',
       'Fundamentals', ARRAY['concept']::text[], 'Which is the correct **logical** processing order of these clauses?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY"},{"label":"B","text":"SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY"},{"label":"C","text":"FROM → SELECT → WHERE → ORDER BY → GROUP BY → HAVING"},{"label":"D","text":"WHERE → FROM → SELECT → GROUP BY → HAVING → ORDER BY"}]'::jsonb, 'A',
       NULL, 0, NULL, 62
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-order-of-execution');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-alias-in-where', 'Why Can''t WHERE See My Alias?', 'mcq', 'Medium', 'Fintech',
       'Fundamentals', ARRAY['concept','alias']::text[], '`SELECT amount * 0.01 AS fee_est FROM transactions WHERE fee_est > 5;` fails.

Why?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"WHERE runs before SELECT, so column aliases don''t exist yet — repeat the expression or use a subquery"},{"label":"B","text":"Aliases can''t contain underscores"},{"label":"C","text":"Multiplication isn''t allowed in SELECT"},{"label":"D","text":"fee_est needs double quotes"}]'::jsonb, 'A',
       NULL, 0, NULL, 58
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-alias-in-where');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-self-join-purpose', 'When Do You Self-Join?', 'mcq', 'Medium', 'Fintech',
       'Self Joins', ARRAY['concept']::text[], 'Detecting "a failed transaction retried by the same user within 30 minutes" joined `transactions` to itself.

What makes a self-join the right tool here?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"The rows being compared live in the same table — a self-join pairs each row with related rows of that table"},{"label":"B","text":"Self-joins are required whenever timestamps are involved"},{"label":"C","text":"It avoids needing a WHERE clause"},{"label":"D","text":"Postgres forbids joining two different tables on time columns"}]'::jsonb, 'A',
       NULL, 0, NULL, 63
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-self-join-purpose');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'district-growth-report', 'Case: District Growth One-Pager', 'case_study', 'Medium', 'Fintech',
       'Joins', ARRAY['group-by','report']::text[], '**Scenario.** The country manager''s one-pager: per district — users, successful transactions, and volume, in one table.

Return `district`, `users_count`, `txn_count`, and `volume`, by volume descending. Count every user in the district even if the counts come from joins.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.district, COUNT(DISTINCT u.user_id) AS users_count,
       COUNT(t.txn_id) AS txn_count, COALESCE(SUM(t.amount), 0) AS volume
FROM users u LEFT JOIN transactions t ON t.user_id = u.user_id AND t.status = ''success''
GROUP BY u.district ORDER BY volume DESC;',
       '["LEFT JOIN with the status filter in the ON clause","COUNT(DISTINCT user_id) — transactions duplicate users","COALESCE the volume for silent districts"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 46
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'district-growth-report');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'early-payoff-candidates', 'Case: Early Payoff Candidates', 'case_study', 'Hard', 'Fintech',
       'Subqueries', ARRAY['cte','ratio']::text[], '**Scenario.** Marketing wants to offer early-payoff discounts to *active* borrowers who have already repaid **at least 30%** of principal — they finish loans, and they come back.

Return `borrower`, `principal`, `repaid`, and `pct_done` (1 decimal), most complete first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'WITH repaid AS (
  SELECT loan_id, SUM(amount) AS total FROM repayments GROUP BY loan_id
)
SELECT l.borrower, l.principal, rp.total AS repaid,
       ROUND(100.0 * rp.total / l.principal, 1) AS pct_done
FROM loans l JOIN repaid rp ON rp.loan_id = l.loan_id
WHERE l.status = ''active'' AND rp.total >= 0.3 * l.principal
ORDER BY pct_done DESC;',
       '["Repayments per loan in a CTE","The 30% test compares two columns — plain WHERE works after the join","Active loans only"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 33
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'early-payoff-candidates');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'cash-in-concentration', 'Case: Deposit Concentration Risk', 'case_study', 'Hard', 'Fintech',
       'Window Functions', ARRAY['share','window']::text[], '**Scenario.** Treasury''s concentration rule: no single user should contribute more than 25% of total successful cash-in.

Return every user''s `name`, `cash_in_total`, and `pct_of_total` (1 decimal), flagging the rule with `breaches_rule` (true/false), largest share first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.name, SUM(t.amount) AS cash_in_total,
       ROUND(100.0 * SUM(t.amount) / SUM(SUM(t.amount)) OVER (), 1) AS pct_of_total,
       (SUM(t.amount) > 0.25 * SUM(SUM(t.amount)) OVER ()) AS breaches_rule
FROM users u JOIN transactions t ON t.user_id = u.user_id
WHERE t.txn_type = ''cash_in'' AND t.status = ''success''
GROUP BY u.name ORDER BY cash_in_total DESC;',
       '["Grand total beside each group: SUM(SUM(...)) OVER ()","The flag is just a boolean expression in SELECT","Filter to successful cash-in before grouping"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 30
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'cash-in-concentration');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mission-launch-day', 'Mission: Merchant Payments Launch Day', 'root', 'Medium', 'Fintech',
       'Investigation', ARRAY['mission','payments']::text[], '**The story.** Your MFS just launched merchant payments with a cashback splash. It''s day one plus a week; the CPO walks over: "Is payment actually becoming a habit, or did we buy a spike?" Four steps through the wallet data to an honest answer.',
       '', '', '',
       '[]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 46
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mission-launch-day');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'catalog-size-per-category', 'Catalog Size per Category', 'code', 'Easy', 'E-Commerce',
       'Aggregation', ARRAY['group-by','count']::text[], 'Return each product `category` and how many products it carries (`products_count`), alphabetical.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT category, COUNT(*) AS products_count FROM products GROUP BY category ORDER BY category;',
       '["One GROUP BY over products","Alphabetical = ORDER BY category"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 90
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'catalog-size-per-category');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'orders-this-june', 'June Order Log', 'code', 'Easy', 'E-Commerce',
       'Filtering', ARRAY['date']::text[], 'Return `order_id`, `customer_id`, and `status` of orders placed in June 2026, newest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT order_id, customer_id, status FROM orders
WHERE order_date >= ''2026-06-01'' AND order_date < ''2026-07-01''
ORDER BY order_date DESC;',
       '["Half-open date range for the month","Newest first = ORDER BY order_date DESC"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 87
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'orders-this-june');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'expensive-line-items', 'Big-Ticket Line Items', 'code', 'Easy', 'E-Commerce',
       'Filtering', ARRAY['arithmetic','where']::text[], 'Return `order_id`, `product_id`, and line value (`line_value` = quantity × unit price) of line items worth over ৳3,000, largest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT order_id, product_id, quantity * unit_price AS line_value
FROM order_items WHERE quantity * unit_price > 3000 ORDER BY line_value DESC;',
       '["Compute the product in both SELECT and WHERE (aliases aren''t visible to WHERE)","Largest first = ORDER BY the computed value DESC"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 74
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'expensive-line-items');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'customer-lifetime-value', 'Simple Customer Lifetime Value', 'code', 'Medium', 'E-Commerce',
       'Joins', ARRAY['multi-join','sum']::text[], 'Return each customer `name` and their all-time **delivered** revenue (`ltv`), highest first. Customers with no delivered orders show ৳0.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT c.name, COALESCE(SUM(oi.quantity * oi.unit_price), 0) AS ltv
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.customer_id AND o.status = ''delivered''
LEFT JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY c.name ORDER BY ltv DESC;',
       '["Keep zero-revenue customers: LEFT JOINs with the status filter in ON","COALESCE(SUM(...), 0)"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 52
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'customer-lifetime-value');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'category-mix-of-orders', 'Categories Inside Each Order', 'code', 'Medium', 'E-Commerce',
       'Joins', ARRAY['count-distinct']::text[], 'Cross-category orders signal browsing, not searching. Return `order_id` and the number of **distinct categories** in it (`categories`), most first, ties by order_id.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT oi.order_id, COUNT(DISTINCT p.category) AS categories
FROM order_items oi JOIN products p ON p.product_id = oi.product_id
GROUP BY oi.order_id ORDER BY categories DESC, oi.order_id;',
       '["Category comes from products","COUNT(DISTINCT category) per order"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 63
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'category-mix-of-orders');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'price-vs-sold-price', 'Sold Below List Price?', 'code', 'Medium', 'E-Commerce',
       'Joins', ARRAY['comparison']::text[], 'Audit pricing drift: line items whose `unit_price` differs from the product''s current list `price`. Return `order_id`, product `name`, `unit_price`, and list `price`. (Zero rows would mean no drift — the data has some.)',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT oi.order_id, p.name, oi.unit_price, p.price
FROM order_items oi JOIN products p ON p.product_id = oi.product_id
WHERE oi.unit_price <> p.price;',
       '["Compare the two price columns after the join","<> is not-equals"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 68
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'price-vs-sold-price');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'first-and-latest-order-dates', 'First and Latest Order per Customer', 'code', 'Medium', 'E-Commerce',
       'Aggregation', ARRAY['min-max']::text[], 'Return each ordering customer''s `name`, `first_order`, and `latest_order` dates, earliest first-order first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT c.name, MIN(o.order_date) AS first_order, MAX(o.order_date) AS latest_order
FROM customers c JOIN orders o ON o.customer_id = c.customer_id
GROUP BY c.name ORDER BY first_order;',
       '["MIN and MAX of the same column","Group per customer"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 76
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'first-and-latest-order-dates');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'quantity-share-per-product', 'Each Product''s Share of Units', 'code', 'Hard', 'E-Commerce',
       'Window Functions', ARRAY['share','window']::text[], 'Across **delivered** orders, return product `name`, `units`, and `pct_of_units` (share of all delivered units, 1 decimal), biggest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT p.name, SUM(oi.quantity) AS units,
       ROUND(100.0 * SUM(oi.quantity) / SUM(SUM(oi.quantity)) OVER (), 1) AS pct_of_units
FROM products p
JOIN order_items oi ON oi.product_id = p.product_id
JOIN orders o ON o.order_id = oi.order_id
WHERE o.status = ''delivered''
GROUP BY p.name ORDER BY units DESC;',
       '["Delivered filter first","Grand total via SUM(SUM(...)) OVER ()"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 38
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'quantity-share-per-product');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'order-value-percentile-band', 'Quartile Bands for Order Values', 'code', 'Hard', 'E-Commerce',
       'Window Functions', ARRAY['ntile']::text[], 'Split **delivered** orders into 4 value quartiles with NTILE. Return `order_id`, `order_value`, and `quartile` (1 = highest values), by value descending.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT order_id, order_value, NTILE(4) OVER (ORDER BY order_value DESC) AS quartile
FROM (
  SELECT o.order_id, SUM(oi.quantity * oi.unit_price) AS order_value
  FROM orders o JOIN order_items oi ON oi.order_id = o.order_id
  WHERE o.status = ''delivered''
  GROUP BY o.order_id
) t ORDER BY order_value DESC;',
       '["Per-order values first","NTILE(4) over the ordered set"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 36
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'order-value-percentile-band');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-distinct-position', 'Where Does DISTINCT Apply?', 'mcq', 'Easy', 'E-Commerce',
       'Fundamentals', ARRAY['distinct']::text[], '`SELECT DISTINCT city, name FROM customers;`

What is de-duplicated?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"Whole result rows — the (city, name) pairs"},{"label":"B","text":"Only the city column"},{"label":"C","text":"Only the name column"},{"label":"D","text":"Nothing without ORDER BY"}]'::jsonb, 'A',
       NULL, 0, NULL, 71
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-distinct-position');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-coalesce-ltv', 'Why COALESCE in LTV Reports?', 'mcq', 'Medium', 'E-Commerce',
       'NULL Semantics', ARRAY['coalesce','left-join']::text[], 'A customer-lifetime-value query LEFT JOINs orders and computes `SUM(quantity * unit_price)`. Customers with no orders show **NULL** LTV.

What''s the standard fix?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"COALESCE(SUM(...), 0) — turn the empty-group NULL into zero"},{"label":"B","text":"Switch to INNER JOIN"},{"label":"C","text":"Add WHERE quantity IS NOT NULL"},{"label":"D","text":"Use COUNT instead of SUM"}]'::jsonb, 'A',
       NULL, 0, NULL, 66
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-coalesce-ltv');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-except-behavior', 'What Does EXCEPT Return?', 'mcq', 'Medium', 'E-Commerce',
       'Set Operations', ARRAY['except']::text[], '`SELECT product_id FROM products EXCEPT SELECT product_id FROM order_items;`

What is this?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"Products that were never ordered — rows in the first set but not the second"},{"label":"B","text":"Products ordered more than once"},{"label":"C","text":"The union of both sets"},{"label":"D","text":"A syntax error; EXCEPT needs JOIN"}]'::jsonb, 'A',
       NULL, 0, NULL, 64
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-except-behavior');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-orderby-multiple', 'Multi-Column ORDER BY', 'mcq', 'Easy', 'E-Commerce',
       'Sorting', ARRAY['order-by']::text[], '`ORDER BY category ASC, price DESC` sorts how?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"By category alphabetically; within each category, most expensive first"},{"label":"B","text":"By price first, then category"},{"label":"C","text":"Randomly within categories"},{"label":"D","text":"It errors — directions must match"}]'::jsonb, 'A',
       NULL, 0, NULL, 83
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-orderby-multiple');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'reorder-stock-signal', 'Case: What to Restock First', 'case_study', 'Medium', 'E-Commerce',
       'Joins', ARRAY['group-by','inventory']::text[], '**Scenario.** The warehouse restocks weekly by demand. Rank products by units in **delivered + processing** orders (live demand), returning `name`, `category`, and `demand_units`, highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT p.name, p.category, SUM(oi.quantity) AS demand_units
FROM products p
JOIN order_items oi ON oi.product_id = p.product_id
JOIN orders o ON o.order_id = oi.order_id
WHERE o.status IN (''delivered'',''processing'')
GROUP BY p.name, p.category
ORDER BY demand_units DESC;',
       '["Demand statuses via IN","Units = SUM(quantity)"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 55
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'reorder-stock-signal');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'vip-cutoff-analysis', 'Case: Drawing the VIP Line', 'case_study', 'Hard', 'E-Commerce',
       'Window Functions', ARRAY['cume','rank']::text[], '**Scenario.** Loyalty wants a VIP tier for customers who drive the top of revenue. Rank ordering customers by delivered revenue and show the running cumulative share.

Return `name`, `revenue`, `rank`, and `cumulative_pct` (running share of total delivered revenue, 1 decimal), best first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'WITH per_customer AS (
  SELECT c.name, SUM(oi.quantity * oi.unit_price) AS revenue
  FROM customers c
  JOIN orders o ON o.customer_id = c.customer_id
  JOIN order_items oi ON oi.order_id = o.order_id
  WHERE o.status = ''delivered''
  GROUP BY c.name
)
SELECT name, revenue,
       RANK() OVER (ORDER BY revenue DESC) AS rank,
       ROUND(100.0 * SUM(revenue) OVER (ORDER BY revenue DESC) / SUM(revenue) OVER (), 1) AS cumulative_pct
FROM per_customer ORDER BY revenue DESC;',
       '["Revenue per customer in a CTE","Running total: SUM(...) OVER (ORDER BY revenue DESC)","Divide by the grand total window"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 28
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'vip-cutoff-analysis');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mission-stockout-scare', 'Mission: The Stockout Scare', 'root', 'Medium', 'E-Commerce',
       'Investigation', ARRAY['mission','inventory']::text[], '**The story.** Friday 6 pm: the ops channel erupts — "Power Banks are about to stock out and campaign traffic is still climbing." You own the numbers. Four steps to tell procurement exactly what''s burning, how fast, and who''s affected.',
       '', '', '',
       '[]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 47
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mission-stockout-scare');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'sylhet-routes', 'Sylhet Route Sheet', 'code', 'Easy', 'Logistics',
       'Filtering', ARRAY['or','where']::text[], 'The Sylhet hub audits its lanes. Return `parcel_id`, `sender_area`, and `receiver_area` of parcels touching **Zindabazar or Ambarkhana** on either end, by parcel_id.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT parcel_id, sender_area, receiver_area FROM parcels
WHERE sender_area IN (''Zindabazar'',''Ambarkhana'') OR receiver_area IN (''Zindabazar'',''Ambarkhana'')
ORDER BY parcel_id;',
       '["Check both columns","IN lists keep the OR readable"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 78
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'sylhet-routes');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'avg-parcel-weight', 'Average Parcel Weight by COD Type', 'code', 'Easy', 'Logistics',
       'Conditional Aggregation', ARRAY['case','avg']::text[], 'Do COD parcels weigh more? Return two labelled rows — `''cod''` and `''prepaid''` (`parcel_type`) — each with `avg_weight` (2 decimals).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT CASE WHEN cod_amount > 0 THEN ''cod'' ELSE ''prepaid'' END AS parcel_type,
       ROUND(AVG(weight_kg), 2) AS avg_weight
FROM parcels GROUP BY 1 ORDER BY parcel_type;',
       '["CASE creates the label, GROUP BY 1 groups on it","ROUND(AVG(...), 2)"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 70
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'avg-parcel-weight');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'june-4-manifest', 'Pickup Manifest for 4 June', 'code', 'Easy', 'Logistics',
       'Date Functions', ARRAY['date','cast']::text[], 'Print the manifest: `delivery_id`, `parcel_id`, and rider `name` for pickups on **4 June 2026**, in pickup order.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT d.delivery_id, d.parcel_id, r.name
FROM deliveries d JOIN riders r ON r.rider_id = d.rider_id
WHERE d.picked_at::date = ''2026-06-04''
ORDER BY d.picked_at;',
       '["Cast picked_at to ::date for a whole-day match","Pickup order = ORDER BY picked_at"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 75
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'june-4-manifest');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'rider-utilization', 'Rider Utilization Snapshot', 'code', 'Medium', 'Logistics',
       'Joins', ARRAY['left-join','count']::text[], 'HR asks who''s idle. Return **every** rider''s `name` and attempt count (`attempts`), including riders with zero, least busy first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT r.name, COUNT(d.delivery_id) AS attempts
FROM riders r LEFT JOIN deliveries d ON d.rider_id = r.rider_id
GROUP BY r.name ORDER BY attempts, name;',
       '["LEFT JOIN keeps idle riders","COUNT(d.delivery_id) ignores the NULL rows"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 64
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'rider-utilization');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'cod-value-at-risk', 'COD Value Still on the Road', 'code', 'Medium', 'Logistics',
       'Subqueries', ARRAY['exists','cod']::text[], 'Finance''s exposure number: total COD of parcels that have **no delivered attempt yet**. One row: `cod_at_risk`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT SUM(p.cod_amount) AS cod_at_risk
FROM parcels p
WHERE p.cod_amount > 0
  AND NOT EXISTS (
    SELECT 1 FROM deliveries d WHERE d.parcel_id = p.parcel_id AND d.status = ''delivered''
  );',
       '["NOT EXISTS over delivered attempts","Only COD parcels carry risk"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 53
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'cod-value-at-risk');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'weight-vs-duration', 'Do Heavy Parcels Travel Slower?', 'code', 'Medium', 'Logistics',
       'Date Arithmetic', ARRAY['case','avg']::text[], 'Compare average delivery hours for parcels **≤ 1.5 kg** vs **> 1.5 kg** (delivered runs). Return `weight_class` (''light''/''heavy'') and `avg_hours` (1 decimal).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT CASE WHEN p.weight_kg <= 1.5 THEN ''light'' ELSE ''heavy'' END AS weight_class,
       ROUND(AVG(EXTRACT(EPOCH FROM (d.delivered_at - d.picked_at)) / 3600)::numeric, 1) AS avg_hours
FROM parcels p JOIN deliveries d ON d.parcel_id = p.parcel_id
WHERE d.status = ''delivered''
GROUP BY 1 ORDER BY weight_class DESC;',
       '["Bucket by weight with CASE","Hours from the EPOCH of the interval"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 51
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'weight-vs-duration');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'busiest-receiver-areas', 'Busiest Receiver Areas', 'code', 'Medium', 'Logistics',
       'Aggregation', ARRAY['group-by','limit']::text[], 'Where should the next dark store go? Return the top 3 `receiver_area`s by parcel count (`parcels_in`), most first, ties alphabetical.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT receiver_area, COUNT(*) AS parcels_in
FROM parcels GROUP BY receiver_area
ORDER BY parcels_in DESC, receiver_area LIMIT 3;',
       '["Count per receiver_area","Deterministic ties need a second sort key"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 73
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'busiest-receiver-areas');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'hub-cod-exposure', 'COD Exposure per Hub', 'code', 'Hard', 'Logistics',
       'Joins', ARRAY['multi-join','exposure']::text[], 'Which hub carries the cash risk? Sum COD of parcels whose **latest attempt** is not delivered, per the attempting rider''s hub. Return hub `city` and `exposure`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'WITH latest AS (
  SELECT d.*, ROW_NUMBER() OVER (PARTITION BY parcel_id ORDER BY picked_at DESC) AS rn
  FROM deliveries d
)
SELECT h.city, SUM(p.cod_amount) AS exposure
FROM latest l
JOIN parcels p ON p.parcel_id = l.parcel_id
JOIN riders r ON r.rider_id = l.rider_id
JOIN hubs h ON h.hub_id = r.hub_id
WHERE l.rn = 1 AND l.status <> ''delivered'' AND p.cod_amount > 0
GROUP BY h.city ORDER BY exposure DESC;',
       '["Latest attempt via ROW_NUMBER ... ORDER BY picked_at DESC","Join up to hubs through riders","Only COD parcels count"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 27
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'hub-cod-exposure');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-groupby-expression', 'GROUP BY 1 — What Does It Mean?', 'mcq', 'Easy', 'Logistics',
       'Aggregation', ARRAY['group-by']::text[], 'You''ll see `GROUP BY 1` in analyst SQL.

What does the `1` refer to?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"The first expression in the SELECT list"},{"label":"B","text":"The first row of the table"},{"label":"C","text":"The primary key"},{"label":"D","text":"It groups everything into one group"}]'::jsonb, 'A',
       NULL, 0, NULL, 69
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-groupby-expression');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-not-exists-vs-not-in-null', 'The NOT IN NULL Trap', 'mcq', 'Hard', 'Logistics',
       'NULL Semantics', ARRAY['not-in','null']::text[], '`WHERE parcel_id NOT IN (SELECT parcel_id FROM deliveries)` silently returns **zero rows** if the subquery emits a single NULL.

Why — and what''s the safe pattern?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"NOT IN with a NULL makes every comparison unknown; use NOT EXISTS instead"},{"label":"B","text":"NOT IN sorts the list first and NULL breaks sorting; add ORDER BY"},{"label":"C","text":"It''s a Postgres bug fixed by DISTINCT"},{"label":"D","text":"The subquery needs LIMIT"}]'::jsonb, 'A',
       NULL, 0, NULL, 41
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-not-exists-vs-not-in-null');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-count-star-vs-column', 'Three Kinds of COUNT', 'mcq', 'Easy', 'Logistics',
       'Aggregation', ARRAY['count']::text[], 'Rank these by what they count: `COUNT(*)`, `COUNT(delivered_at)`, `COUNT(DISTINCT rider_id)`.',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"All rows; rows where delivered_at is non-NULL; unique rider ids"},{"label":"B","text":"They all count the same thing"},{"label":"C","text":"Non-NULL rows; all rows; all rider rows"},{"label":"D","text":"COUNT(*) errors on NULL columns"}]'::jsonb, 'A',
       NULL, 0, NULL, 77
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-count-star-vs-column');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'rider-scorecard', 'Case: The Rider Scorecard', 'case_study', 'Hard', 'Logistics',
       'Conditional Aggregation', ARRAY['scorecard','ratio']::text[], '**Scenario.** Monthly rider reviews use one scorecard: attempts, completions, failures, and completion rate.

Per rider with any attempts, return `name`, `attempts`, `completed`, `failed`, and `completion_pct` (completed ÷ attempts × 100, 1 decimal), best rate first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT r.name, COUNT(*) AS attempts,
       COUNT(*) FILTER (WHERE d.status = ''delivered'') AS completed,
       COUNT(*) FILTER (WHERE d.status = ''failed'') AS failed,
       ROUND(100.0 * COUNT(*) FILTER (WHERE d.status = ''delivered'') / COUNT(*), 1) AS completion_pct
FROM riders r JOIN deliveries d ON d.rider_id = r.rider_id
GROUP BY r.name ORDER BY completion_pct DESC, name;',
       '["FILTER-ed COUNTs share one GROUP BY pass","Rate = completed / attempts with 100.0 for float math"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 34
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'rider-scorecard');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mission-peak-day', 'Mission: Surviving Peak Day', 'root', 'Medium', 'Logistics',
       'Investigation', ARRAY['mission','capacity']::text[], '**The story.** The 11.11 mega-sale hits in three weeks and last year the network buckled. The COO wants a capacity read from normal-week data: where parcels flow, who carries the load, and where a surge would snap first. Four steps to the capacity memo.',
       '', '', '',
       '[]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 45
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mission-peak-day');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'plan-price-list', 'The Tariff Sheet', 'code', 'Easy', 'Telco',
       'Sorting', ARRAY['order-by']::text[], 'Return every plan''s `name`, `monthly_fee`, and `data_gb`, cheapest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT name, monthly_fee, data_gb FROM plans ORDER BY monthly_fee;',
       '["No filter — the whole tariff sheet, sorted","Cheapest first = ORDER BY monthly_fee"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 93
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'plan-price-list');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'taka-per-gb', 'Taka per GB by Plan', 'code', 'Easy', 'Telco',
       'Numeric Functions', ARRAY['arithmetic','round']::text[], 'Value-for-money check: per plan, `name` and `taka_per_gb` (monthly fee ÷ allowance GB, 2 decimals), best value first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT name, ROUND(monthly_fee / data_gb, 2) AS taka_per_gb
FROM plans ORDER BY taka_per_gb;',
       '["Simple division per row","Best value = smallest ratio"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 82
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'taka-per-gb');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'chattogram-subscribers', 'Chattogram Base', 'code', 'Easy', 'Telco',
       'Joins', ARRAY['join','where']::text[], 'Return Chattogram subscribers with their plan: `name`, plan name (`plan_name`), `activated_on`, by activation date.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, p.name AS plan_name, s.activated_on
FROM subscribers s JOIN plans p ON p.plan_id = s.plan_id
WHERE s.district = ''Chattogram'' ORDER BY s.activated_on;',
       '["Alias the second name column","District filter on subscribers"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 85
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'chattogram-subscribers');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'recharge-frequency', 'Recharge Frequency', 'code', 'Medium', 'Telco',
       'Joins', ARRAY['left-join','count']::text[], 'Per subscriber — **including those who never recharged** — return `name` and `recharge_count`, most frequent first, ties by name.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, COUNT(r.recharge_id) AS recharge_count
FROM subscribers s LEFT JOIN recharges r ON r.sub_id = s.sub_id
GROUP BY s.name ORDER BY recharge_count DESC, name;',
       '["LEFT JOIN + COUNT(column) counts only real recharges","Ties broken by name in ORDER BY"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 71
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'recharge-frequency');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'zero-voice-days', 'Data-Only Days', 'code', 'Medium', 'Telco',
       'Filtering', ARRAY['comparison']::text[], 'Voice is dying — prove it. Return `name`, `usage_date`, and `data_mb` for subscriber-days with **under 10 voice minutes**, heaviest data first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, u.usage_date, u.data_mb
FROM subscribers s JOIN usage_daily u ON u.sub_id = s.sub_id
WHERE u.voice_min < 10 ORDER BY u.data_mb DESC;',
       '["Row-level filter, no aggregation needed","Heaviest data first = ORDER BY data_mb DESC"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 74
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'zero-voice-days');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'district-arpu-gap', 'District Recharge Gap', 'code', 'Medium', 'Telco',
       'Aggregation', ARRAY['group-by','avg']::text[], 'Where does recharge money come from? Per subscriber `district`: `total_recharge` and `avg_recharge` per top-up (2 decimals), highest total first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.district, SUM(r.amount) AS total_recharge, ROUND(AVG(r.amount), 2) AS avg_recharge
FROM subscribers s JOIN recharges r ON r.sub_id = s.sub_id
GROUP BY s.district ORDER BY total_recharge DESC;',
       '["Join recharges through subscribers for the district","SUM and AVG in one pass"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 66
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'district-arpu-gap');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'consecutive-usage-growth', 'Two Days of Growth in a Row', 'code', 'Hard', 'Telco',
       'Window Functions', ARRAY['lag','trend']::text[], 'Find subscriber-days where data usage grew versus the **previous day** for that subscriber. Return `name`, `usage_date`, `data_mb`, and `prev_mb`, largest jump first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT name, usage_date, data_mb, prev_mb FROM (
  SELECT s.name, u.usage_date, u.data_mb,
         LAG(u.data_mb) OVER (PARTITION BY u.sub_id ORDER BY u.usage_date) AS prev_mb
  FROM subscribers s JOIN usage_daily u ON u.sub_id = s.sub_id
) t WHERE prev_mb IS NOT NULL AND data_mb > prev_mb
ORDER BY data_mb - prev_mb DESC;',
       '["LAG per subscriber ordered by date","Growth = current > previous","First day per subscriber has NULL prev"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 36
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'consecutive-usage-growth');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'plan-upgrade-shortlist', 'The Upgrade Shortlist', 'code', 'Hard', 'Telco',
       'Subqueries', ARRAY['cte','comparison']::text[], 'Sales wants subscribers whose average daily data, projected to 30 days, **exceeds their plan''s allowance**. Return `name`, plan `allowance_gb`, and `projected_gb` (30 × daily average ÷ 1024, 1 decimal), biggest overshoot first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'WITH daily AS (
  SELECT sub_id, AVG(data_mb) AS avg_mb FROM usage_daily GROUP BY sub_id
)
SELECT s.name, p.data_gb AS allowance_gb,
       ROUND(30 * d.avg_mb / 1024.0, 1) AS projected_gb
FROM subscribers s
JOIN plans p ON p.plan_id = s.plan_id
JOIN daily d ON d.sub_id = s.sub_id
WHERE 30 * d.avg_mb / 1024.0 > p.data_gb
ORDER BY 30 * d.avg_mb / 1024.0 - p.data_gb DESC;',
       '["Daily average per subscriber in a CTE","Project: 30 × avg ÷ 1024 GB","Compare against the plan allowance in WHERE"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 30
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'plan-upgrade-shortlist');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-having-without-groupby', 'HAVING Without GROUP BY', 'mcq', 'Hard', 'Telco',
       'Aggregation', ARRAY['having']::text[], 'Is `SELECT SUM(amount) FROM recharges HAVING SUM(amount) > 1000;` valid SQL?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"Yes — the whole table is one implicit group, and HAVING filters that group"},{"label":"B","text":"No — HAVING always requires GROUP BY"},{"label":"C","text":"Only in MySQL, not Postgres"},{"label":"D","text":"Yes, but it behaves exactly like WHERE"}]'::jsonb, 'A',
       NULL, 0, NULL, 43
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-having-without-groupby');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-integer-division', 'The Integer Division Trap', 'mcq', 'Medium', 'Telco',
       'Numeric Functions', ARRAY['division']::text[], '`data_mb` is an INT. A teammate computes GB with `SUM(data_mb) / 1024` and the decimals vanish.

What happened, and the fix?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"Integer ÷ integer truncates in Postgres; divide by 1024.0 (or cast) to keep decimals"},{"label":"B","text":"SUM always rounds; use TOTAL instead"},{"label":"C","text":"The column needs an index"},{"label":"D","text":"GB conversion requires the pg_units extension"}]'::jsonb, 'A',
       NULL, 0, NULL, 59
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-integer-division');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-view-of-latest-row', 'Latest Row per Group — Idiom Check', 'mcq', 'Medium', 'Telco',
       'Window Functions', ARRAY['concept','row-number']::text[], '"Latest recharge per subscriber" — which is the standard window idiom?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"ROW_NUMBER() OVER (PARTITION BY sub_id ORDER BY recharged_at DESC), then keep rn = 1"},{"label":"B","text":"MAX(recharged_at) alone, selecting all other columns freely"},{"label":"C","text":"ORDER BY recharged_at DESC LIMIT 1 (one row for the whole table is fine)"},{"label":"D","text":"DISTINCT sub_id with no ordering"}]'::jsonb, 'A',
       NULL, 0, NULL, 56
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-view-of-latest-row');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'recharge-behavior-segments', 'Case: Recharge Behaviour Segments', 'case_study', 'Medium', 'Telco',
       'Conditional Aggregation', ARRAY['bucketing','segments']::text[], '**Scenario.** CVM segments the base by top-up style: `''big_ticket''` (average recharge ≥ ৳300), `''regular''` (৳150–299), `''micro''` (< ৳150).

Per recharging subscriber: `name`, `avg_recharge` (2 decimals), and `segment`, largest average first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, ROUND(AVG(r.amount), 2) AS avg_recharge,
       CASE WHEN AVG(r.amount) >= 300 THEN ''big_ticket''
            WHEN AVG(r.amount) >= 150 THEN ''regular''
            ELSE ''micro'' END AS segment
FROM subscribers s JOIN recharges r ON r.sub_id = s.sub_id
GROUP BY s.name ORDER BY avg_recharge DESC;',
       '["Segment on the AVG aggregate with CASE","The CASE can reference AVG(...) directly in SELECT"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 52
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'recharge-behavior-segments');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'quiet-then-gone', 'Case: Quiet Before the Churn', 'case_study', 'Hard', 'Telco',
       'Subqueries', ARRAY['anti-join','date']::text[], '**Scenario.** Churn theory: subscribers go quiet on recharges *after* the first week of June while still burning data.

Return `name` and total June-recorded data (`data_mb_total`) of subscribers with **no recharge after 5 June 2026**, heaviest user first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, SUM(u.data_mb) AS data_mb_total
FROM subscribers s JOIN usage_daily u ON u.sub_id = s.sub_id
WHERE NOT EXISTS (
  SELECT 1 FROM recharges r
  WHERE r.sub_id = s.sub_id AND r.recharged_at > ''2026-06-05''
)
GROUP BY s.name ORDER BY data_mb_total DESC;',
       '["NOT EXISTS with the date cutoff inside","Still join usage for the data total"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 35
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'quiet-then-gone');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'launch-1-payment-count', 'Step 1: Raw Adoption', 'code', 'Easy', 'Fintech',
       'Aggregation', ARRAY['count','where']::text[], 'Baseline: one row with successful payment count (`payments`) and their total value (`payment_volume`).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT COUNT(*) AS payments, SUM(amount) AS payment_volume
FROM transactions WHERE txn_type = ''payment'' AND status = ''success'';',
       '["Filter to successful payments","Two aggregates, no GROUP BY"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-launch-day'), 0, NULL, 83
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'launch-1-payment-count');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'launch-2-payer-profile', 'Step 2: Who Pays?', 'code', 'Medium', 'Fintech',
       'Joins', ARRAY['join','group-by']::text[], 'Profile the payers by geography: per `district`, distinct paying users (`payers`) and payment volume (`volume`), by volume descending.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.district, COUNT(DISTINCT u.user_id) AS payers, SUM(t.amount) AS volume
FROM users u JOIN transactions t ON t.user_id = u.user_id
WHERE t.txn_type = ''payment'' AND t.status = ''success''
GROUP BY u.district ORDER BY volume DESC;',
       '["COUNT(DISTINCT user_id) for unique payers","Same payment filter as step 1"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-launch-day'), 1, NULL, 61
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'launch-2-payer-profile');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'launch-3-repeat-payers', 'Step 3: The Habit Signal', 'code', 'Medium', 'Fintech',
       'Aggregation', ARRAY['having']::text[], 'A habit means spending from the wallet, not just topping it up. Return `user_id` and spend count (`spend_count`) of users with **2 or more** successful spend transactions (payments or send-money combined).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT user_id, COUNT(*) AS spend_count
FROM transactions
WHERE txn_type IN (''payment'',''send_money'') AND status = ''success''
GROUP BY user_id HAVING COUNT(*) >= 2
ORDER BY spend_count DESC;',
       '["Spend = payment + send_money via IN","HAVING COUNT(*) >= 2"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-launch-day'), 2, NULL, 66
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'launch-3-repeat-payers');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'launch-4-wallet-share', 'Step 4: Share of Wallet', 'code', 'Hard', 'Fintech',
       'Conditional Aggregation', ARRAY['case-when','ratio']::text[], 'The honest answer: for each user who made any successful payment, what share of their total successful spend (payments + send_money) went to payments? Return `user_id`, `payment_total`, `spend_total`, and `payment_share_pct` (1 decimal), highest share first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT user_id,
       SUM(CASE WHEN txn_type = ''payment'' THEN amount ELSE 0 END) AS payment_total,
       SUM(amount) AS spend_total,
       ROUND(100.0 * SUM(CASE WHEN txn_type = ''payment'' THEN amount ELSE 0 END) / SUM(amount), 1) AS payment_share_pct
FROM transactions
WHERE status = ''success'' AND txn_type IN (''payment'',''send_money'')
GROUP BY user_id
HAVING SUM(CASE WHEN txn_type = ''payment'' THEN amount ELSE 0 END) > 0
ORDER BY payment_share_pct DESC;',
       '["Restrict the universe to payment + send_money in WHERE","Payment share via conditional SUM over the full SUM","HAVING keeps actual payers"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-launch-day'), 3, 1800, 32
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'launch-4-wallet-share');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'stockout-1-velocity', 'Step 1: Sales Velocity', 'code', 'Easy', 'E-Commerce',
       'Aggregation', ARRAY['group-by','sum']::text[], 'Which products move? Return `name` and total units across **all non-cancelled** orders (`units_moved`), fastest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT p.name, SUM(oi.quantity) AS units_moved
FROM products p
JOIN order_items oi ON oi.product_id = p.product_id
JOIN orders o ON o.order_id = oi.order_id
WHERE o.status <> ''cancelled''
GROUP BY p.name ORDER BY units_moved DESC;',
       '["Exclude cancelled with <>","SUM(quantity) per product"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-stockout-scare'), 0, NULL, 79
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'stockout-1-velocity');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'stockout-2-hero-buyers', 'Step 2: Who Buys the Hero Product?', 'code', 'Medium', 'E-Commerce',
       'Joins', ARRAY['multi-join','where']::text[], 'Zoom into the **Power Bank 20000mAh**: return each buying customer''s `name`, `city`, order `status`, and `quantity`, by quantity descending.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT c.name, c.city, o.status, oi.quantity
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
JOIN products p ON p.product_id = oi.product_id
WHERE p.name = ''Power Bank 20000mAh''
ORDER BY oi.quantity DESC;',
       '["Four tables chained by keys","Filter on the product name"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-stockout-scare'), 1, NULL, 62
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'stockout-2-hero-buyers');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'stockout-3-city-demand', 'Step 3: Demand by City', 'code', 'Medium', 'E-Commerce',
       'Joins', ARRAY['group-by']::text[], 'Warehouse allocation needs geography: for Electronics products (non-cancelled orders), return `city` and `units`, highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT c.city, SUM(oi.quantity) AS units
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
JOIN products p ON p.product_id = oi.product_id
WHERE p.category = ''Electronics'' AND o.status <> ''cancelled''
GROUP BY c.city ORDER BY units DESC;',
       '["Same 4-table chain, category filter this time","Group by city"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-stockout-scare'), 2, NULL, 58
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'stockout-3-city-demand');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'stockout-4-substitutes', 'Step 4: The Substitute Pitch', 'code', 'Hard', 'E-Commerce',
       'Subqueries', ARRAY['not-in','same-category']::text[], 'If the Power Bank stocks out, what do we push instead? Return other **Electronics** products with their delivered-order units (`units_sold`, 0 if never sold), best sellers first — excluding the Power Bank itself.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT p.name,
       COALESCE(SUM(oi.quantity) FILTER (WHERE o.status = ''delivered''), 0) AS units_sold
FROM products p
LEFT JOIN order_items oi ON oi.product_id = p.product_id
LEFT JOIN orders o ON o.order_id = oi.order_id
WHERE p.category = ''Electronics'' AND p.name <> ''Power Bank 20000mAh''
GROUP BY p.name ORDER BY units_sold DESC;',
       '["LEFT JOINs keep never-sold substitutes","FILTER (or CASE) restricts the SUM to delivered","Exclude the hero product in WHERE"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-stockout-scare'), 3, 1800, 31
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'stockout-4-substitutes');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'peak-1-flow-map', 'Step 1: The Flow Map', 'code', 'Easy', 'Logistics',
       'Aggregation', ARRAY['group-by']::text[], 'Map the lanes: return `sender_area`, `receiver_area`, and parcel count (`parcels`) per lane, busiest first, ties by sender then receiver.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT sender_area, receiver_area, COUNT(*) AS parcels
FROM parcels GROUP BY sender_area, receiver_area
ORDER BY parcels DESC, sender_area, receiver_area;',
       '["Group by both endpoints","Stable ordering with extra sort keys"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-peak-day'), 0, NULL, 80
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'peak-1-flow-map');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'peak-2-daily-throughput', 'Step 2: Daily Throughput', 'code', 'Medium', 'Logistics',
       'Date Functions', ARRAY['date','group-by']::text[], 'Capacity is a daily number. Return each pickup day (`day`) with attempts started (`pickups`) and completions (`delivered`), chronological.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT picked_at::date AS day, COUNT(*) AS pickups,
       COUNT(*) FILTER (WHERE status = ''delivered'') AS delivered
FROM deliveries GROUP BY picked_at::date ORDER BY day;',
       '["Group by the pickup date","Completions via a FILTERed COUNT"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-peak-day'), 1, NULL, 57
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'peak-2-daily-throughput');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'peak-3-rider-load-balance', 'Step 3: Load Balance Check', 'code', 'Medium', 'Logistics',
       'Window Functions', ARRAY['share']::text[], 'Is work spread evenly? Per rider: `name`, `attempts`, and `pct_of_attempts` across the whole network (1 decimal), heaviest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT r.name, COUNT(*) AS attempts,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct_of_attempts
FROM riders r JOIN deliveries d ON d.rider_id = r.rider_id
GROUP BY r.name ORDER BY attempts DESC;',
       '["SUM(COUNT(*)) OVER () is the network total","Share = rider / network"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-peak-day'), 2, NULL, 48
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'peak-3-rider-load-balance');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'peak-4-fragile-lanes', 'Step 4: The Fragile Lanes', 'code', 'Hard', 'Logistics',
       'Joins', ARRAY['failure-rate','group-by']::text[], 'Finale: lanes that already show cracks. Per receiver_area with any attempts, return `receiver_area`, `attempts`, `non_delivered` (failed or still in transit), and `risk_pct` (1 decimal), riskiest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT p.receiver_area, COUNT(*) AS attempts,
       COUNT(*) FILTER (WHERE d.status <> ''delivered'') AS non_delivered,
       ROUND(100.0 * COUNT(*) FILTER (WHERE d.status <> ''delivered'') / COUNT(*), 1) AS risk_pct
FROM parcels p JOIN deliveries d ON d.parcel_id = p.parcel_id
GROUP BY p.receiver_area
HAVING COUNT(*) FILTER (WHERE d.status <> ''delivered'') > 0
ORDER BY risk_pct DESC;',
       '["Non-delivered = status <> ''delivered'' on attempts","HAVING keeps only lanes with cracks","Rate needs 100.0 float math"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-peak-day'), 3, 1800, 29
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'peak-4-fragile-lanes');

DROP TABLE _worlds;
