-- Question Library seed: tranche1 (50 questions).
-- Generated by scripts/generate-careerprep-migration.ts from supabase/seed/careerprep/tranche1.ts
-- Idempotent: each insert is guarded by slug.

CREATE TEMP TABLE _worlds (name text PRIMARY KEY, schema_sql text, initial_sql text);

INSERT INTO _worlds VALUES
  ('fintech_wallet', 'CREATE TABLE users (
  user_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  district TEXT NOT NULL,
  joined_at DATE NOT NULL,
  kyc_verified BOOLEAN NOT NULL
);
CREATE TABLE agents (
  agent_id INT PRIMARY KEY,
  shop_name TEXT NOT NULL,
  district TEXT NOT NULL
);
CREATE TABLE transactions (
  txn_id INT PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(user_id),
  agent_id INT REFERENCES agents(agent_id),
  txn_type TEXT NOT NULL, -- ''cash_in'' | ''cash_out'' | ''send_money'' | ''payment''
  amount NUMERIC(12,2) NOT NULL,
  fee NUMERIC(10,2) NOT NULL DEFAULT 0,
  txn_at TIMESTAMP NOT NULL,
  status TEXT NOT NULL -- ''success'' | ''failed'' | ''reversed''
);', 'INSERT INTO users VALUES
  (1,''Rahim Uddin'',''Dhaka'',''2025-11-03'',true),
  (2,''Karima Akter'',''Chattogram'',''2025-12-18'',true),
  (3,''Sabbir Hossain'',''Dhaka'',''2026-01-25'',false),
  (4,''Nusrat Jahan'',''Sylhet'',''2026-02-07'',true),
  (5,''Tanvir Ahmed'',''Khulna'',''2026-02-19'',true),
  (6,''Mim Chowdhury'',''Dhaka'',''2026-03-12'',false),
  (7,''Arif Islam'',''Rajshahi'',''2026-04-02'',true),
  (8,''Farzana Haque'',''Chattogram'',''2026-04-28'',true);
INSERT INTO agents VALUES
  (101,''Bhai Bhai Telecom'',''Dhaka''),
  (102,''Ma Enterprise'',''Chattogram''),
  (103,''Padma Store'',''Rajshahi''),
  (104,''Digital Point'',''Dhaka'');
INSERT INTO transactions VALUES
  (1001,1,101,''cash_in'',5000.00,0,''2026-06-01 09:15:00'',''success''),
  (1002,1,NULL,''send_money'',1200.00,5.00,''2026-06-01 12:40:00'',''success''),
  (1003,2,102,''cash_in'',8000.00,0,''2026-06-02 10:05:00'',''success''),
  (1004,2,102,''cash_out'',3000.00,55.50,''2026-06-03 16:22:00'',''success''),
  (1005,3,101,''cash_in'',2000.00,0,''2026-06-03 18:30:00'',''success''),
  (1006,3,NULL,''payment'',450.00,0,''2026-06-04 11:00:00'',''success''),
  (1007,4,NULL,''send_money'',2500.00,10.00,''2026-06-04 14:45:00'',''failed''),
  (1008,4,NULL,''send_money'',2500.00,10.00,''2026-06-04 14:52:00'',''success''),
  (1009,5,104,''cash_in'',12000.00,0,''2026-06-05 09:00:00'',''success''),
  (1010,5,104,''cash_out'',7000.00,129.50,''2026-06-05 19:10:00'',''success''),
  (1011,1,NULL,''payment'',890.00,0,''2026-06-06 08:20:00'',''success''),
  (1012,6,101,''cash_in'',1500.00,0,''2026-06-06 13:33:00'',''success''),
  (1013,6,NULL,''send_money'',700.00,5.00,''2026-06-07 10:11:00'',''reversed''),
  (1014,7,103,''cash_in'',6000.00,0,''2026-06-07 15:55:00'',''success''),
  (1015,7,103,''cash_out'',2000.00,37.00,''2026-06-08 09:47:00'',''success''),
  (1016,8,102,''cash_in'',9500.00,0,''2026-06-08 11:28:00'',''success''),
  (1017,8,NULL,''payment'',1250.00,0,''2026-06-09 17:05:00'',''success''),
  (1018,2,NULL,''send_money'',4000.00,10.00,''2026-06-10 12:00:00'',''success''),
  (1019,5,NULL,''payment'',3200.00,0,''2026-06-10 20:15:00'',''success''),
  (1020,1,101,''cash_out'',2500.00,46.25,''2026-06-11 10:30:00'',''success''),
  (1021,4,102,''cash_in'',3000.00,0,''2026-06-11 14:00:00'',''success''),
  (1022,7,NULL,''send_money'',900.00,5.00,''2026-06-12 09:05:00'',''success''),
  (1023,8,102,''cash_out'',5000.00,92.50,''2026-06-12 18:40:00'',''failed''),
  (1024,8,102,''cash_out'',5000.00,92.50,''2026-06-12 18:47:00'',''success'');'),
  ('ecommerce_shop', 'CREATE TABLE customers (
  customer_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  signup_date DATE NOT NULL
);
CREATE TABLE products (
  product_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC(10,2) NOT NULL
);
CREATE TABLE orders (
  order_id INT PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customers(customer_id),
  order_date DATE NOT NULL,
  status TEXT NOT NULL -- ''delivered'' | ''cancelled'' | ''returned'' | ''processing''
);
CREATE TABLE order_items (
  order_id INT NOT NULL REFERENCES orders(order_id),
  product_id INT NOT NULL REFERENCES products(product_id),
  quantity INT NOT NULL,
  unit_price NUMERIC(10,2) NOT NULL,
  PRIMARY KEY (order_id, product_id)
);', 'INSERT INTO customers VALUES
  (1,''Shorna Rahman'',''Dhaka'',''2025-10-11''),
  (2,''Imran Kabir'',''Chattogram'',''2025-12-02''),
  (3,''Priya Das'',''Dhaka'',''2026-01-15''),
  (4,''Rakib Hasan'',''Sylhet'',''2026-02-20''),
  (5,''Lamia Islam'',''Khulna'',''2026-03-08''),
  (6,''Fahim Chowdhury'',''Dhaka'',''2026-04-19'');
INSERT INTO products VALUES
  (11,''Wireless Earbuds'',''Electronics'',2490.00),
  (12,''Cotton Panjabi'',''Fashion'',1850.00),
  (13,''Blender 500W'',''Home Appliance'',3200.00),
  (14,''Yoga Mat'',''Sports'',990.00),
  (15,''Power Bank 20000mAh'',''Electronics'',1750.00),
  (16,''Deshi Cotton Saree'',''Fashion'',2950.00),
  (17,''LED Desk Lamp'',''Home Appliance'',780.00),
  (18,''Gaming Mouse'',''Electronics'',1450.00);
INSERT INTO orders VALUES
  (501,1,''2026-05-02'',''delivered''),
  (502,2,''2026-05-04'',''delivered''),
  (503,1,''2026-05-10'',''returned''),
  (504,3,''2026-05-12'',''delivered''),
  (505,4,''2026-05-15'',''cancelled''),
  (506,5,''2026-05-18'',''delivered''),
  (507,3,''2026-05-21'',''delivered''),
  (508,6,''2026-05-25'',''processing''),
  (509,2,''2026-06-01'',''delivered''),
  (510,1,''2026-06-05'',''delivered'');
INSERT INTO order_items VALUES
  (501,11,1,2490.00),(501,14,2,990.00),
  (502,12,1,1850.00),
  (503,13,1,3200.00),
  (504,15,2,1750.00),(504,17,1,780.00),
  (505,16,1,2950.00),
  (506,11,1,2490.00),(506,15,1,1750.00),
  (507,14,1,990.00),(507,17,2,780.00),
  (508,13,1,3200.00),
  (509,16,2,2950.00),(509,12,1,1850.00),
  (510,15,1,1750.00);'),
  ('logistics_courier', 'CREATE TABLE hubs (
  hub_id INT PRIMARY KEY,
  city TEXT NOT NULL
);
CREATE TABLE riders (
  rider_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  hub_id INT NOT NULL REFERENCES hubs(hub_id)
);
CREATE TABLE parcels (
  parcel_id INT PRIMARY KEY,
  sender_area TEXT NOT NULL,
  receiver_area TEXT NOT NULL,
  weight_kg NUMERIC(6,2) NOT NULL,
  cod_amount NUMERIC(10,2) NOT NULL, -- cash on delivery, 0 = prepaid
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE deliveries (
  delivery_id INT PRIMARY KEY,
  parcel_id INT NOT NULL REFERENCES parcels(parcel_id),
  rider_id INT NOT NULL REFERENCES riders(rider_id),
  picked_at TIMESTAMP NOT NULL,
  delivered_at TIMESTAMP, -- NULL = not delivered yet
  status TEXT NOT NULL -- ''delivered'' | ''in_transit'' | ''failed''
);', 'INSERT INTO hubs VALUES (1,''Dhaka''),(2,''Chattogram''),(3,''Sylhet'');
INSERT INTO riders VALUES
  (21,''Jashim Uddin'',1),(22,''Selim Reza'',1),(23,''Polash Mia'',2),
  (24,''Hridoy Khan'',2),(25,''Shuvo Roy'',3);
INSERT INTO parcels VALUES
  (301,''Uttara'',''Dhanmondi'',1.20,1500.00,''2026-06-01 08:00:00''),
  (302,''Banani'',''Mirpur'',0.50,0,''2026-06-01 09:30:00''),
  (303,''Agrabad'',''Nasirabad'',2.80,3200.00,''2026-06-01 10:15:00''),
  (304,''Gulshan'',''Uttara'',0.90,850.00,''2026-06-02 08:45:00''),
  (305,''Zindabazar'',''Ambarkhana'',1.50,2100.00,''2026-06-02 11:20:00''),
  (306,''Dhanmondi'',''Banani'',3.40,0,''2026-06-03 09:00:00''),
  (307,''Mirpur'',''Gulshan'',0.75,650.00,''2026-06-03 14:30:00''),
  (308,''Nasirabad'',''Agrabad'',1.10,1200.00,''2026-06-04 10:00:00''),
  (309,''Uttara'',''Mirpur'',2.00,1800.00,''2026-06-04 15:45:00''),
  (310,''Ambarkhana'',''Zindabazar'',0.60,0,''2026-06-05 09:10:00'');
INSERT INTO deliveries VALUES
  (401,301,21,''2026-06-01 10:00:00'',''2026-06-01 15:30:00'',''delivered''),
  (402,302,22,''2026-06-01 11:00:00'',''2026-06-01 13:45:00'',''delivered''),
  (403,303,23,''2026-06-01 12:30:00'',''2026-06-02 17:00:00'',''delivered''),
  (404,304,21,''2026-06-02 10:30:00'',''2026-06-02 14:20:00'',''delivered''),
  (405,305,25,''2026-06-02 13:00:00'',NULL,''in_transit''),
  (406,306,22,''2026-06-03 11:00:00'',''2026-06-04 10:30:00'',''delivered''),
  (407,307,21,''2026-06-03 16:00:00'',NULL,''failed''),
  (408,307,22,''2026-06-04 09:00:00'',''2026-06-04 12:15:00'',''delivered''),
  (409,308,24,''2026-06-04 11:30:00'',''2026-06-04 18:40:00'',''delivered''),
  (410,309,21,''2026-06-05 08:30:00'',NULL,''in_transit''),
  (411,310,25,''2026-06-05 10:00:00'',''2026-06-05 12:00:00'',''delivered'');'),
  ('telco_network', 'CREATE TABLE plans (
  plan_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  monthly_fee NUMERIC(8,2) NOT NULL,
  data_gb INT NOT NULL
);
CREATE TABLE subscribers (
  sub_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  plan_id INT NOT NULL REFERENCES plans(plan_id),
  activated_on DATE NOT NULL,
  district TEXT NOT NULL
);
CREATE TABLE recharges (
  recharge_id INT PRIMARY KEY,
  sub_id INT NOT NULL REFERENCES subscribers(sub_id),
  amount NUMERIC(8,2) NOT NULL,
  recharged_at TIMESTAMP NOT NULL
);
CREATE TABLE usage_daily (
  sub_id INT NOT NULL REFERENCES subscribers(sub_id),
  usage_date DATE NOT NULL,
  data_mb INT NOT NULL,
  voice_min INT NOT NULL,
  PRIMARY KEY (sub_id, usage_date)
);', 'INSERT INTO plans VALUES
  (1,''Bondhu 199'',199.00,5),(2,''Shadhin 349'',349.00,15),
  (3,''Power 599'',599.00,40),(4,''Business 999'',999.00,100);
INSERT INTO subscribers VALUES
  (61,''Mahmud Hasan'',1,''2025-09-14'',''Dhaka''),
  (62,''Rima Sultana'',2,''2025-11-30'',''Chattogram''),
  (63,''Joy Barua'',2,''2026-01-08'',''Chattogram''),
  (64,''Sadia Afrin'',3,''2026-02-14'',''Dhaka''),
  (65,''Nayeem Islam'',1,''2026-03-22'',''Rajshahi''),
  (66,''Tania Akter'',4,''2026-04-05'',''Dhaka'');
INSERT INTO recharges VALUES
  (901,61,199.00,''2026-06-01 08:00:00''),
  (902,62,349.00,''2026-06-01 09:30:00''),
  (903,63,100.00,''2026-06-02 12:00:00''),
  (904,63,249.00,''2026-06-03 10:15:00''),
  (905,64,599.00,''2026-06-03 18:20:00''),
  (906,65,199.00,''2026-06-04 11:00:00''),
  (907,66,999.00,''2026-06-05 09:45:00''),
  (908,61,50.00,''2026-06-08 20:30:00''),
  (909,62,100.00,''2026-06-10 14:10:00'');
INSERT INTO usage_daily VALUES
  (61,''2026-06-01'',350,22),(61,''2026-06-02'',420,15),(61,''2026-06-03'',180,40),
  (62,''2026-06-01'',900,10),(62,''2026-06-02'',1150,8),(62,''2026-06-03'',600,25),
  (63,''2026-06-01'',450,30),(63,''2026-06-02'',380,45),(63,''2026-06-03'',720,12),
  (64,''2026-06-01'',2100,5),(64,''2026-06-02'',1800,18),(64,''2026-06-03'',2500,7),
  (65,''2026-06-01'',120,60),(65,''2026-06-02'',90,75),(65,''2026-06-03'',200,55),
  (66,''2026-06-01'',3400,20),(66,''2026-06-02'',4100,35),(66,''2026-06-03'',2900,28);');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'verified-wallet-users', 'List KYC-Verified Wallet Users', 'code', 'Easy', 'Fintech',
       'Filtering', ARRAY['select','where']::text[], 'Compliance needs a list of all KYC-verified wallet users.

Return `user_id`, `name`, and `district` of every user whose KYC is verified, ordered by `user_id`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT user_id, name, district FROM users WHERE kyc_verified = true ORDER BY user_id;',
       '["kyc_verified is a boolean column","Filter with WHERE, then ORDER BY user_id"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 82
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'verified-wallet-users');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'large-successful-transactions', 'Large Successful Transactions', 'code', 'Easy', 'Fintech',
       'Filtering', ARRAY['where','and']::text[], 'The risk team monitors big movements. Return `txn_id`, `user_id`, `txn_type`, and `amount` for every **successful** transaction of more than ৳5,000, newest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT txn_id, user_id, txn_type, amount FROM transactions WHERE status = ''success'' AND amount > 5000 ORDER BY txn_at DESC;',
       '["Combine two conditions with AND","Newest first means ORDER BY txn_at DESC"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 78
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'large-successful-transactions');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'transactions-by-type', 'Transaction Mix by Type', 'code', 'Easy', 'Fintech',
       'Aggregation', ARRAY['group-by','count']::text[], 'Product wants the transaction mix. For each `txn_type`, return the type and the number of transactions (`txn_count`), highest count first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT txn_type, COUNT(*) AS txn_count FROM transactions GROUP BY txn_type ORDER BY txn_count DESC;',
       '["GROUP BY txn_type","COUNT(*) counts rows per group"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 75
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'transactions-by-type');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'agent-cash-out-volume', 'Cash-Out Volume per Agent', 'code', 'Medium', 'Fintech',
       'Joins', ARRAY['join','group-by','sum']::text[], 'Agent operations ranks agent points by the cash they pay out.

For each agent, return `shop_name`, `district`, and total **successful** `cash_out` amount as `total_cash_out`, highest first. Only include agents that have at least one successful cash-out.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT a.shop_name, a.district, SUM(t.amount) AS total_cash_out
FROM agents a
JOIN transactions t ON t.agent_id = a.agent_id
WHERE t.txn_type = ''cash_out'' AND t.status = ''success''
GROUP BY a.shop_name, a.district
ORDER BY total_cash_out DESC;',
       '["JOIN transactions to agents on agent_id","Filter type and status in WHERE before grouping","SUM(amount) per agent"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 61
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'agent-cash-out-volume');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'daily-transaction-volume', 'Daily Transaction Volume (First Week of June)', 'code', 'Medium', 'Fintech',
       'Aggregation', ARRAY['date','group-by']::text[], 'Finance tracks daily volume. For 1–7 June 2026, return each day (`txn_date`) and the total amount of **successful** transactions (`daily_volume`), ordered by day.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT txn_at::date AS txn_date, SUM(amount) AS daily_volume
FROM transactions
WHERE status = ''success'' AND txn_at >= ''2026-06-01'' AND txn_at < ''2026-06-08''
GROUP BY txn_at::date
ORDER BY txn_date;',
       '["Cast the timestamp to a date with ::date","Bound the range with >= and <","GROUP BY the casted date"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 58
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'daily-transaction-volume');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'users-with-clean-history', 'Users with a Clean Transaction History', 'code', 'Medium', 'Fintech',
       'Subqueries', ARRAY['not-exists','anti-join']::text[], 'Support wants users who have **never** had a failed or reversed transaction.

Return `user_id` and `name` of those users, ordered by `user_id`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.user_id, u.name
FROM users u
WHERE NOT EXISTS (
  SELECT 1 FROM transactions t
  WHERE t.user_id = u.user_id AND t.status IN (''failed'',''reversed'')
)
ORDER BY u.user_id;',
       '["Think anti-join: users with no matching bad transaction","NOT EXISTS with a correlated subquery","status IN (''failed'',''reversed'')"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 49
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'users-with-clean-history');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'top-payers', 'Top 3 Users by Payment Spend', 'code', 'Medium', 'Fintech',
       'Aggregation', ARRAY['group-by','limit','join']::text[], 'Merchant payments is the growth bet. Return the top 3 users by total successful `payment` amount: `name` and `total_paid`, highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.name, SUM(t.amount) AS total_paid
FROM users u
JOIN transactions t ON t.user_id = u.user_id
WHERE t.txn_type = ''payment'' AND t.status = ''success''
GROUP BY u.name
ORDER BY total_paid DESC
LIMIT 3;',
       '["Join, filter to successful payments, group by user","ORDER BY ... DESC LIMIT 3"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 56
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'top-payers');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'largest-transaction-per-user', 'Each User''s Largest Transaction', 'code', 'Hard', 'Fintech',
       'Window Functions', ARRAY['row-number','partition']::text[], 'For every user who has at least one successful transaction, return `name`, `txn_type`, and `amount` of their **single largest** successful transaction. Break amount ties by earliest `txn_at`. Order by `name`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT name, txn_type, amount FROM (
  SELECT u.name, t.txn_type, t.amount,
         ROW_NUMBER() OVER (PARTITION BY u.user_id ORDER BY t.amount DESC, t.txn_at ASC) AS rn
  FROM users u
  JOIN transactions t ON t.user_id = u.user_id
  WHERE t.status = ''success''
) ranked
WHERE rn = 1
ORDER BY name;',
       '["ROW_NUMBER() OVER (PARTITION BY user ORDER BY amount DESC)","Wrap in a subquery and keep rn = 1","Tie-break inside the window''s ORDER BY"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 38
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'largest-transaction-per-user');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'running-cash-in-volume', 'Running Cash-In Volume', 'code', 'Hard', 'Fintech',
       'Window Functions', ARRAY['window','running-total']::text[], 'Treasury watches liquidity build up. For successful `cash_in` transactions, return each day (`txn_date`), that day''s total (`day_total`), and the running cumulative total (`running_total`) ordered by day.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT txn_date, day_total, SUM(day_total) OVER (ORDER BY txn_date) AS running_total
FROM (
  SELECT txn_at::date AS txn_date, SUM(amount) AS day_total
  FROM transactions
  WHERE txn_type = ''cash_in'' AND status = ''success''
  GROUP BY txn_at::date
) d
ORDER BY txn_date;',
       '["First aggregate per day in a subquery","SUM(...) OVER (ORDER BY day) gives a running total"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 34
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'running-cash-in-volume');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-left-join-semantics', 'Which JOIN Keeps All Left Rows?', 'mcq', 'Easy', 'Fintech',
       'Joins', ARRAY['concept']::text[], 'Your query must list **every wallet user**, with their agent transactions where they exist — users without any agent transaction must still appear.

Which join does this?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"INNER JOIN"},{"label":"B","text":"LEFT JOIN"},{"label":"C","text":"RIGHT JOIN"},{"label":"D","text":"CROSS JOIN"}]'::jsonb, 'B',
       NULL, 0, NULL, 80
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-left-join-semantics');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-count-nullable-column', 'COUNT(*) vs COUNT(agent_id)', 'mcq', 'Easy', 'Fintech',
       'Aggregation', ARRAY['count','null']::text[], 'The `transactions` table has 24 rows; 14 of them have a non-NULL `agent_id` (agent-assisted), the other 10 are app-only (`agent_id IS NULL`).

What does this return?

```sql
SELECT COUNT(*), COUNT(agent_id) FROM transactions;
```',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), '',
       '[]'::jsonb, '[{"label":"A","text":"24 and 24"},{"label":"B","text":"24 and 10"},{"label":"C","text":"24 and 14"},{"label":"D","text":"14 and 14"}]'::jsonb, 'C',
       NULL, 0, NULL, 66
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-count-nullable-column');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-null-equality', 'What Does NULL = NULL Evaluate To?', 'mcq', 'Medium', 'Fintech',
       'NULL Semantics', ARRAY['concept','null']::text[], 'A teammate filters app-only transactions with `WHERE agent_id = NULL` and gets zero rows even though NULLs exist.

In SQL, what does the comparison `NULL = NULL` evaluate to?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"TRUE"},{"label":"B","text":"FALSE"},{"label":"C","text":"NULL (unknown) — which is why IS NULL must be used"},{"label":"D","text":"It raises an error"}]'::jsonb, 'C',
       NULL, 0, NULL, 57
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-null-equality');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-cash-out-sum', 'Predict the Cash-Out Total', 'mcq', 'Medium', 'Fintech',
       'Aggregation', ARRAY['sum','where']::text[], 'Successful cash-outs in the dataset are: ৳3,000, ৳7,000, ৳2,000, ৳2,500 and ৳5,000 (one cash-out of ৳5,000 failed and was retried).

What does this return?

```sql
SELECT SUM(amount) FROM transactions
WHERE txn_type = ''cash_out'' AND status = ''success'';
```',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), '',
       '[]'::jsonb, '[{"label":"A","text":"24500"},{"label":"B","text":"19500"},{"label":"C","text":"14500"},{"label":"D","text":"22000"}]'::jsonb, 'B',
       NULL, 0, NULL, 62
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-cash-out-sum');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'duplicate-send-money-attempts', 'Case: Duplicate Send-Money Attempts', 'case_study', 'Medium', 'Fintech',
       'Aggregation', ARRAY['group-by','having','fraud']::text[], '**Scenario.** Customer support at an MFS keeps hearing "I sent money twice by mistake." Ops wants a daily duplicate report.

Find user/amount/day combinations with **more than one** `send_money` attempt (any status). Return `user_id`, the amount, the day (`txn_date`), and the attempt count.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT user_id, amount, txn_at::date AS txn_date, COUNT(*) AS attempts
FROM transactions
WHERE txn_type = ''send_money''
GROUP BY user_id, amount, txn_at::date
HAVING COUNT(*) > 1;',
       '["Group by user, amount and day together","HAVING COUNT(*) > 1 keeps only duplicates","Any status — don''t filter on status"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 47
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'duplicate-send-money-attempts');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'agent-settlement-report', 'Case: Agent Settlement Report', 'case_study', 'Hard', 'Fintech',
       'Conditional Aggregation', ARRAY['case-when','group-by']::text[], '**Scenario.** Every evening, finance settles cash with agent points: cash-in raises the agent''s e-money balance, cash-out lowers it.

For each agent with successful activity, return `shop_name`, total successful cash-in (`cash_in_total`), total successful cash-out (`cash_out_total`), and `net_float` = cash_in − cash_out. Order by `net_float` descending.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT a.shop_name,
       SUM(CASE WHEN t.txn_type = ''cash_in''  THEN t.amount ELSE 0 END) AS cash_in_total,
       SUM(CASE WHEN t.txn_type = ''cash_out'' THEN t.amount ELSE 0 END) AS cash_out_total,
       SUM(CASE WHEN t.txn_type = ''cash_in''  THEN t.amount ELSE 0 END)
     - SUM(CASE WHEN t.txn_type = ''cash_out'' THEN t.amount ELSE 0 END) AS net_float
FROM agents a
JOIN transactions t ON t.agent_id = a.agent_id
WHERE t.status = ''success''
GROUP BY a.shop_name
ORDER BY net_float DESC;',
       '["One row per agent means one GROUP BY with conditional SUMs","SUM(CASE WHEN type=''cash_in'' THEN amount ELSE 0 END)","Net float is the difference of the two conditional sums"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 36
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'agent-settlement-report');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mission-fraud-week', 'Mission: Fraud Week at an MFS', 'root', 'Medium', 'Fintech',
       'Investigation', ARRAY['mission','fraud']::text[], '**The story.** Monday morning, the risk dashboard at your MFS lights up: failed transactions spiked over the weekend. You''re the analyst on call. Over the next four steps you''ll work the same wallet dataset like a real investigation — from a first headcount of the damage to naming the accounts that need a manual review.

Complete the steps in order; each one builds on what the previous step told you.',
       '', '', '',
       '[]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 45
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mission-fraud-week');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'electronics-catalog', 'Electronics Catalog by Price', 'code', 'Easy', 'E-Commerce',
       'Filtering', ARRAY['where','order-by']::text[], 'Merchandising wants the Electronics lineup. Return `name` and `price` of every product in the **Electronics** category, most expensive first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT name, price FROM products WHERE category = ''Electronics'' ORDER BY price DESC;',
       '["Simple WHERE on category","ORDER BY price DESC"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 85
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'electronics-catalog');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'may-delivered-orders', 'Delivered Orders in May', 'code', 'Easy', 'E-Commerce',
       'Filtering', ARRAY['date','where']::text[], 'Return `order_id`, `customer_id`, and `order_date` of all orders placed in **May 2026** that were delivered, oldest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT order_id, customer_id, order_date
FROM orders
WHERE status = ''delivered'' AND order_date >= ''2026-05-01'' AND order_date < ''2026-06-01''
ORDER BY order_date;',
       '["Bound May with >= ''2026-05-01'' AND < ''2026-06-01''","Also filter status = ''delivered''"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 76
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'may-delivered-orders');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'order-revenue', 'Revenue per Delivered Order', 'code', 'Medium', 'E-Commerce',
       'Joins', ARRAY['join','group-by','sum']::text[], 'Finance reconciles order values from line items. For every **delivered** order, return `order_id` and its revenue (`order_revenue` = sum of quantity × unit price), highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT o.order_id, SUM(oi.quantity * oi.unit_price) AS order_revenue
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status = ''delivered''
GROUP BY o.order_id
ORDER BY order_revenue DESC;',
       '["Revenue lives in order_items: quantity * unit_price","Join and GROUP BY order_id"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 63
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'order-revenue');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'revenue-by-city', 'Delivered Revenue by City', 'code', 'Medium', 'E-Commerce',
       'Joins', ARRAY['multi-join','group-by']::text[], 'Where is the money coming from? Return each customer `city` and its total delivered revenue (`city_revenue`), highest first. Revenue is quantity × unit price of items on delivered orders.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT c.city, SUM(oi.quantity * oi.unit_price) AS city_revenue
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status = ''delivered''
GROUP BY c.city
ORDER BY city_revenue DESC;',
       '["Chain two joins: customers → orders → order_items","Filter delivered before grouping by city"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 59
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'revenue-by-city');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'never-ordered-products', 'Products Nobody Has Ordered', 'code', 'Medium', 'E-Commerce',
       'Subqueries', ARRAY['anti-join','left-join']::text[], 'Catalog cleanup: find products that appear in **no order at all**. Return `product_id`, `name`, and `category`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT p.product_id, p.name, p.category
FROM products p
LEFT JOIN order_items oi ON oi.product_id = p.product_id
WHERE oi.product_id IS NULL;',
       '["LEFT JOIN order_items and keep the rows with no match","The no-match test is oi.product_id IS NULL"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 54
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'never-ordered-products');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'biggest-order-per-customer', 'Each Customer''s Biggest Order', 'code', 'Hard', 'E-Commerce',
       'Window Functions', ARRAY['window','rank']::text[], 'For every customer with at least one delivered order, return `name`, `order_id`, and the revenue of their **highest-revenue delivered order** (`order_revenue`). Order by revenue descending.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT name, order_id, order_revenue FROM (
  SELECT c.name, o.order_id, SUM(oi.quantity * oi.unit_price) AS order_revenue,
         ROW_NUMBER() OVER (PARTITION BY c.customer_id ORDER BY SUM(oi.quantity * oi.unit_price) DESC) AS rn
  FROM customers c
  JOIN orders o ON o.customer_id = c.customer_id
  JOIN order_items oi ON oi.order_id = o.order_id
  WHERE o.status = ''delivered''
  GROUP BY c.customer_id, c.name, o.order_id
) t
WHERE rn = 1
ORDER BY order_revenue DESC;',
       '["First compute revenue per order (GROUP BY)","Then ROW_NUMBER() partitioned by customer over that aggregate","Keep rn = 1"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 35
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'biggest-order-per-customer');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-where-vs-having', 'WHERE vs HAVING', 'mcq', 'Easy', 'E-Commerce',
       'Aggregation', ARRAY['concept']::text[], 'You need "cities with more than ৳10,000 of delivered revenue". A teammate asks why `WHERE SUM(...) > 10000` throws an error.

What''s the correct statement?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"WHERE filters rows before aggregation; HAVING filters groups after aggregation"},{"label":"B","text":"HAVING is just a faster version of WHERE"},{"label":"C","text":"WHERE works on aggregates if you add parentheses"},{"label":"D","text":"HAVING can only be used with COUNT"}]'::jsonb, 'A',
       NULL, 0, NULL, 74
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-where-vs-having');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-distinct-buyers', 'Predict the Distinct Buyer Count', 'mcq', 'Medium', 'E-Commerce',
       'Aggregation', ARRAY['distinct','count']::text[], 'Delivered orders in the dataset belong to customers 1, 2, 3 and 5 — customer 1 has three delivered orders, customers 2 and 3 have two each.

What does this return?

```sql
SELECT COUNT(DISTINCT customer_id) FROM orders WHERE status = ''delivered'';
```',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), '',
       '[]'::jsonb, '[{"label":"A","text":"7"},{"label":"B","text":"4"},{"label":"C","text":"5"},{"label":"D","text":"3"}]'::jsonb, 'B',
       NULL, 0, NULL, 71
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-distinct-buyers');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'return-loss-by-category', 'Case: What Returns Cost Us', 'case_study', 'Medium', 'E-Commerce',
       'Joins', ARRAY['join','group-by','returns']::text[], '**Scenario.** The COO suspects returns are concentrated in a few categories and wants the losses quantified before the next supplier negotiation.

For **returned** orders, return each product `category` and the revenue lost (`lost_revenue` = quantity × unit price), highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT p.category, SUM(oi.quantity * oi.unit_price) AS lost_revenue
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
JOIN products p ON p.product_id = oi.product_id
WHERE o.status = ''returned''
GROUP BY p.category
ORDER BY lost_revenue DESC;',
       '["Three tables: orders → order_items → products","Filter status = ''returned''","Group by product category"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 52
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'return-loss-by-category');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mission-campaign-postmortem', 'Mission: Eid Campaign Postmortem', 'root', 'Medium', 'E-Commerce',
       'Investigation', ARRAY['mission','analytics']::text[], '**The story.** Your marketplace just wrapped its Eid flash-sale campaign. The CMO wants a postmortem by Thursday: did we actually make money, what sold, and who kept coming back? You''ll answer in four steps over the same shop dataset, each digging one level deeper than the last.',
       '', '', '',
       '[]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 48
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mission-campaign-postmortem');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'high-cod-parcels', 'High-Value COD Parcels', 'code', 'Easy', 'Logistics',
       'Filtering', ARRAY['where','order-by']::text[], 'COD parcels above ৳1,000 need extra verification at handover. Return `parcel_id`, `receiver_area`, and `cod_amount` for those parcels, highest COD first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT parcel_id, receiver_area, cod_amount FROM parcels WHERE cod_amount > 1000 ORDER BY cod_amount DESC;',
       '["cod_amount = 0 means prepaid","Simple WHERE + ORDER BY"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 83
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'high-cod-parcels');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'riders-per-hub', 'Rider Headcount per Hub', 'code', 'Easy', 'Logistics',
       'Joins', ARRAY['join','count']::text[], 'Return each hub `city` and how many riders are based there (`rider_count`), highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT h.city, COUNT(*) AS rider_count
FROM hubs h
JOIN riders r ON r.hub_id = h.hub_id
GROUP BY h.city
ORDER BY rider_count DESC;',
       '["Join riders to hubs","COUNT(*) per city"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 77
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'riders-per-hub');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'avg-delivery-hours-per-rider', 'Average Delivery Time per Rider', 'code', 'Medium', 'Logistics',
       'Date Arithmetic', ARRAY['extract','interval','avg']::text[], 'Ops benchmarks riders on speed. For **delivered** runs, return the rider `name` and their average delivery duration in hours (`avg_hours`, rounded to 1 decimal), fastest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT r.name, ROUND(AVG(EXTRACT(EPOCH FROM (d.delivered_at - d.picked_at)) / 3600)::numeric, 1) AS avg_hours
FROM riders r
JOIN deliveries d ON d.rider_id = r.rider_id
WHERE d.status = ''delivered''
GROUP BY r.name
ORDER BY avg_hours;',
       '["delivered_at - picked_at gives an interval","EXTRACT(EPOCH FROM interval) / 3600 converts to hours","Average per rider, then order ascending"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 44
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'avg-delivery-hours-per-rider');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'multi-attempt-parcels', 'Parcels Needing Multiple Attempts', 'code', 'Medium', 'Logistics',
       'Aggregation', ARRAY['group-by','having']::text[], 'A failed attempt means a re-dispatch the next day — expensive. Return `parcel_id` and the number of delivery attempts (`attempts`) for parcels with **more than one** attempt.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT parcel_id, COUNT(*) AS attempts
FROM deliveries
GROUP BY parcel_id
HAVING COUNT(*) > 1;',
       '["Each deliveries row is one attempt","HAVING COUNT(*) > 1"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 65
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'multi-attempt-parcels');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'stuck-parcels-aging', 'Aging Report for Stuck Parcels', 'code', 'Hard', 'Logistics',
       'Date Arithmetic', ARRAY['null','interval','left-join']::text[], 'As of **2026-06-06 00:00:00**, which picked-up parcels are still not delivered? Return `parcel_id`, rider `name`, delivery `status`, and `hours_in_flight` (hours from `picked_at` to that cutoff, rounded to 1 decimal), longest first. Include both in-transit and failed attempts that never delivered — but if a parcel was later delivered by another attempt, exclude it.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT d.parcel_id, r.name, d.status,
       ROUND((EXTRACT(EPOCH FROM (TIMESTAMP ''2026-06-06 00:00:00'' - d.picked_at)) / 3600)::numeric, 1) AS hours_in_flight
FROM deliveries d
JOIN riders r ON r.rider_id = d.rider_id
WHERE d.delivered_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM deliveries d2
    WHERE d2.parcel_id = d.parcel_id AND d2.status = ''delivered''
  )
ORDER BY hours_in_flight DESC;',
       '["Undelivered attempts have delivered_at IS NULL","A parcel rescued by a later attempt must be excluded — NOT EXISTS","Hours = EPOCH difference / 3600 against the fixed cutoff"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 29
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'stuck-parcels-aging');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-primary-key-guarantees', 'What Does a PRIMARY KEY Guarantee?', 'mcq', 'Easy', 'Logistics',
       'Constraints', ARRAY['concept']::text[], 'The `parcels` table declares `parcel_id INT PRIMARY KEY`.

Which pair of guarantees does that give you?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"Uniqueness and NOT NULL"},{"label":"B","text":"Uniqueness and automatic indexing of every other column"},{"label":"C","text":"NOT NULL and automatic foreign keys"},{"label":"D","text":"Sorted physical storage and uniqueness"}]'::jsonb, 'A',
       NULL, 0, NULL, 72
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-primary-key-guarantees');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-null-delivered-count', 'Predict the Undelivered Count', 'mcq', 'Medium', 'Logistics',
       'NULL Semantics', ARRAY['null','count']::text[], 'In `deliveries`, three attempts have no `delivered_at` (one failed attempt and two still in transit).

What does this return?

```sql
SELECT COUNT(*) FROM deliveries WHERE delivered_at IS NULL;
```',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), '',
       '[]'::jsonb, '[{"label":"A","text":"0 — NULLs can''t be counted"},{"label":"B","text":"2"},{"label":"C","text":"3"},{"label":"D","text":"11"}]'::jsonb, 'C',
       NULL, 0, NULL, 75
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-null-delivered-count');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'cod-reconciliation', 'Case: Evening COD Reconciliation', 'case_study', 'Medium', 'Logistics',
       'Joins', ARRAY['join','group-by','cod']::text[], '**Scenario.** Every night the hub accountant collects cash from riders. The sheet must show exactly how much COD each rider collected on **delivered** parcels.

Return rider `name` and `cod_collected` (skip riders who collected nothing), highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT r.name, SUM(p.cod_amount) AS cod_collected
FROM riders r
JOIN deliveries d ON d.rider_id = r.rider_id
JOIN parcels p ON p.parcel_id = d.parcel_id
WHERE d.status = ''delivered'' AND p.cod_amount > 0
GROUP BY r.name
ORDER BY cod_collected DESC;',
       '["COD lives on parcels; the rider link is on deliveries","Only delivered attempts count","cod_amount = 0 parcels are prepaid — exclude them"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 51
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'cod-reconciliation');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'shadhin-plan-subscribers', 'Subscribers on the Shadhin 349 Plan', 'code', 'Easy', 'Telco',
       'Joins', ARRAY['join','where']::text[], 'Return `name` and `district` of every subscriber on the **Shadhin 349** plan, ordered by name.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, s.district
FROM subscribers s
JOIN plans p ON p.plan_id = s.plan_id
WHERE p.name = ''Shadhin 349''
ORDER BY s.name;',
       '["Join subscribers to plans","Filter on the plan''s name column"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 80
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'shadhin-plan-subscribers');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'june-recharges', 'Recharge Log for Early June', 'code', 'Easy', 'Telco',
       'Filtering', ARRAY['where','date']::text[], 'Return `recharge_id`, `sub_id`, and `amount` of recharges of at least ৳199 made from 1–5 June 2026, in time order.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT recharge_id, sub_id, amount
FROM recharges
WHERE amount >= 199 AND recharged_at >= ''2026-06-01'' AND recharged_at < ''2026-06-06''
ORDER BY recharged_at;',
       '["Two conditions: amount and the date window","Half-open range: >= start, < day-after-end"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 79
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'june-recharges');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'data-usage-per-subscriber', 'Total Data Usage per Subscriber', 'code', 'Medium', 'Telco',
       'Aggregation', ARRAY['sum','join','round']::text[], 'Network planning needs consumption per subscriber. Return `name` and total data used in **GB** (`total_gb` = sum of data_mb / 1024, rounded to 2 decimals), heaviest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, ROUND(SUM(u.data_mb) / 1024.0, 2) AS total_gb
FROM subscribers s
JOIN usage_daily u ON u.sub_id = s.sub_id
GROUP BY s.name
ORDER BY total_gb DESC;',
       '["SUM(data_mb) then divide by 1024.0 (float division)","ROUND(x, 2)"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 62
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'data-usage-per-subscriber');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'recharge-revenue-per-plan', 'Recharge Revenue per Plan', 'code', 'Medium', 'Telco',
       'Joins', ARRAY['multi-join','group-by']::text[], 'Which plans bring in the recharge money? Return plan `name` and total recharge amount by its subscribers (`recharge_revenue`), highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT p.name, SUM(r.amount) AS recharge_revenue
FROM plans p
JOIN subscribers s ON s.plan_id = p.plan_id
JOIN recharges r ON r.sub_id = s.sub_id
GROUP BY p.name
ORDER BY recharge_revenue DESC;',
       '["Recharges link to plans through subscribers","Two joins, one GROUP BY"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 57
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'recharge-revenue-per-plan');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'peak-usage-day', 'Each Subscriber''s Peak Data Day', 'code', 'Hard', 'Telco',
       'Window Functions', ARRAY['row-number','partition']::text[], 'For each subscriber, find the day they used the **most data**. Return `name`, `usage_date`, and `data_mb` of that peak day, ordered by data_mb descending.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT name, usage_date, data_mb FROM (
  SELECT s.name, u.usage_date, u.data_mb,
         ROW_NUMBER() OVER (PARTITION BY s.sub_id ORDER BY u.data_mb DESC) AS rn
  FROM subscribers s
  JOIN usage_daily u ON u.sub_id = s.sub_id
) t
WHERE rn = 1
ORDER BY data_mb DESC;',
       '["ROW_NUMBER() OVER (PARTITION BY subscriber ORDER BY data_mb DESC)","Filter to rn = 1 in the outer query"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 39
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'peak-usage-day');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-coalesce-behavior', 'What Does COALESCE Return?', 'mcq', 'Easy', 'Telco',
       'NULL Semantics', ARRAY['concept','coalesce']::text[], 'A report shows blank plan names for some legacy rows, so a teammate writes `COALESCE(plan_name, ''Unknown'')`.

What does `COALESCE` do?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"Returns the first non-NULL argument, left to right"},{"label":"B","text":"Concatenates all of its arguments"},{"label":"C","text":"Replaces NULL with zero, always"},{"label":"D","text":"Returns NULL if any argument is NULL"}]'::jsonb, 'A',
       NULL, 0, NULL, 73
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-coalesce-behavior');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-max-data-usage', 'Predict the Max Daily Usage', 'mcq', 'Medium', 'Telco',
       'Aggregation', ARRAY['max']::text[], 'The heaviest user in the dataset is a Business 999 subscriber whose three daily readings are 3,400 MB, 4,100 MB and 2,900 MB; nobody else crosses 2,500 MB.

What does this return?

```sql
SELECT MAX(data_mb) FROM usage_daily;
```',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), '',
       '[]'::jsonb, '[{"label":"A","text":"10400"},{"label":"B","text":"3400"},{"label":"C","text":"4100"},{"label":"D","text":"2500"}]'::jsonb, 'C',
       NULL, 0, NULL, 84
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-max-data-usage');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'one-time-recharger-churn-risk', 'Case: One-Time Rechargers', 'case_study', 'Medium', 'Telco',
       'Aggregation', ARRAY['having','join','churn']::text[], '**Scenario.** Retention flags subscribers who recharged exactly **once** in June as churn risks — one top-up and silence.

Return `name`, plan name (`plan_name`), and their single recharge `amount`, ordered by amount descending.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, p.name AS plan_name, MAX(r.amount) AS amount
FROM subscribers s
JOIN plans p ON p.plan_id = s.plan_id
JOIN recharges r ON r.sub_id = s.sub_id
GROUP BY s.sub_id, s.name, p.name
HAVING COUNT(r.recharge_id) = 1
ORDER BY amount DESC;',
       '["Group per subscriber and count recharges","HAVING COUNT(...) = 1 keeps one-time rechargers","With exactly one recharge, MAX(amount) is that recharge"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 46
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'one-time-recharger-churn-risk');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'fraud-week-1-damage-count', 'Day 1: Count the Damage', 'code', 'Easy', 'Fintech',
       'Aggregation', ARRAY['group-by','having']::text[], 'First, a headcount. For every user with at least one failed or reversed transaction, return `user_id` and the number of such transactions (`bad_txns`), worst first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT user_id, COUNT(*) AS bad_txns
FROM transactions
WHERE status IN (''failed'',''reversed'')
GROUP BY user_id
ORDER BY bad_txns DESC, user_id;',
       '["Filter to the two bad statuses first","GROUP BY user_id and COUNT(*)"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-fraud-week'), 0, NULL, 70
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'fraud-week-1-damage-count');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'fraud-week-2-retry-pairs', 'Day 2: Find the Retry Pairs', 'code', 'Medium', 'Fintech',
       'Self Joins', ARRAY['self-join','time-window']::text[], 'Day 1 showed the failures. Now check which of them were **retried and succeeded**: find pairs where the same user re-attempted the same type and amount within 30 minutes of a failure and it succeeded.

Return the failed `txn_id` (`failed_txn`), the successful `txn_id` (`retry_txn`), `user_id`, and the amount.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT f.txn_id AS failed_txn, s.txn_id AS retry_txn, f.user_id, f.amount
FROM transactions f
JOIN transactions s
  ON s.user_id = f.user_id
 AND s.txn_type = f.txn_type
 AND s.amount = f.amount
 AND s.status = ''success''
 AND s.txn_at > f.txn_at
 AND s.txn_at <= f.txn_at + INTERVAL ''30 minutes''
WHERE f.status = ''failed'';',
       '["Join transactions to itself on user, type and amount","The retry happens after the failure: s.txn_at > f.txn_at","Bound the window with an INTERVAL"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-fraud-week'), 1, NULL, 41
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'fraud-week-2-retry-pairs');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'fraud-week-3-district-exposure', 'Day 3: District Exposure', 'code', 'Medium', 'Fintech',
       'Joins', ARRAY['join','group-by']::text[], 'Leadership asks: *where* is this happening? Sum the amount of failed and reversed transactions per user district.

Return `district` and `exposed_amount`, highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.district, SUM(t.amount) AS exposed_amount
FROM users u
JOIN transactions t ON t.user_id = u.user_id
WHERE t.status IN (''failed'',''reversed'')
GROUP BY u.district
ORDER BY exposed_amount DESC;',
       '["The district lives on users — join through user_id","Same bad-status filter as Day 1, then GROUP BY district"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-fraud-week'), 2, NULL, 55
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'fraud-week-3-district-exposure');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'fraud-week-4-review-list', 'Day 4: The Manual Review List', 'code', 'Hard', 'Fintech',
       'Conditional Aggregation', ARRAY['case-when','having','ratio']::text[], 'Final step: cash-out-heavy wallets are the classic mule pattern. Flag users whose total successful cash-out exceeds **50%** of their total successful cash-in.

Return `user_id`, `name`, `cash_in_total`, `cash_out_total`. Only include users with at least one successful cash-in.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.user_id, u.name,
       SUM(CASE WHEN t.txn_type = ''cash_in''  THEN t.amount ELSE 0 END) AS cash_in_total,
       SUM(CASE WHEN t.txn_type = ''cash_out'' THEN t.amount ELSE 0 END) AS cash_out_total
FROM users u
JOIN transactions t ON t.user_id = u.user_id
WHERE t.status = ''success''
GROUP BY u.user_id, u.name
HAVING SUM(CASE WHEN t.txn_type = ''cash_in'' THEN t.amount ELSE 0 END) > 0
   AND SUM(CASE WHEN t.txn_type = ''cash_out'' THEN t.amount ELSE 0 END)
     > 0.5 * SUM(CASE WHEN t.txn_type = ''cash_in'' THEN t.amount ELSE 0 END);',
       '["Conditional SUMs give cash-in and cash-out in one pass","The ratio test goes in HAVING, not WHERE","Guard against users with zero cash-in"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-fraud-week'), 3, 1800, 31
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'fraud-week-4-review-list');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'postmortem-1-order-funnel', 'Step 1: The Order Funnel', 'code', 'Easy', 'E-Commerce',
       'Aggregation', ARRAY['group-by','count']::text[], 'Start wide: how did orders end up? Return each order `status` and its count (`order_count`), highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status ORDER BY order_count DESC;',
       '["GROUP BY status","COUNT(*) per group"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-campaign-postmortem'), 0, NULL, 81
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'postmortem-1-order-funnel');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'postmortem-2-aov', 'Step 2: Average Order Value', 'code', 'Medium', 'E-Commerce',
       'Aggregation', ARRAY['avg','subquery']::text[], 'The funnel looked healthy. Now the money: what was the **average order value** of delivered orders? Return one row with `aov` (average of per-order revenue), rounded to 2 decimals.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT ROUND(AVG(order_revenue), 2) AS aov FROM (
  SELECT o.order_id, SUM(oi.quantity * oi.unit_price) AS order_revenue
  FROM orders o
  JOIN order_items oi ON oi.order_id = o.order_id
  WHERE o.status = ''delivered''
  GROUP BY o.order_id
) t;',
       '["Two levels: revenue per order first, then AVG over that","ROUND(x, 2) for the final figure"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-campaign-postmortem'), 1, NULL, 53
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'postmortem-2-aov');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'postmortem-3-bestseller', 'Step 3: The Bestseller', 'code', 'Medium', 'E-Commerce',
       'Joins', ARRAY['join','group-by','limit']::text[], 'Marketing wants the hero product for the recap deck. Among **delivered** orders, return the product `name` and total units sold (`units_sold`) of the single best-selling product by units.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT p.name, SUM(oi.quantity) AS units_sold
FROM products p
JOIN order_items oi ON oi.product_id = p.product_id
JOIN orders o ON o.order_id = oi.order_id
WHERE o.status = ''delivered''
GROUP BY p.name
ORDER BY units_sold DESC
LIMIT 1;',
       '["Units are SUM(quantity), not revenue","ORDER BY DESC LIMIT 1 for the single winner"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-campaign-postmortem'), 2, NULL, 58
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'postmortem-3-bestseller');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'postmortem-4-repeat-buyers', 'Step 4: Repeat Buyers Carry the Campaign', 'code', 'Hard', 'E-Commerce',
       'Aggregation', ARRAY['having','multi-join']::text[], 'The CMO''s hypothesis: repeat buyers drove the campaign. Find customers with **2 or more delivered orders**; return `name`, their delivered order count (`orders_count`), and total delivered revenue (`total_revenue`), by revenue descending.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT c.name, COUNT(DISTINCT o.order_id) AS orders_count,
       SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status = ''delivered''
GROUP BY c.customer_id, c.name
HAVING COUNT(DISTINCT o.order_id) >= 2
ORDER BY total_revenue DESC;',
       '["COUNT(DISTINCT order_id) — line items would inflate a plain COUNT","The ≥2 filter belongs in HAVING","Revenue still comes from order_items"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-campaign-postmortem'), 3, 1800, 33
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'postmortem-4-repeat-buyers');

DROP TABLE _worlds;
