-- Question Library seed: tranche2 (74 questions).
-- Generated by scripts/generate-careerprep-migration.ts from supabase/seed/careerprep/tranche2.ts
-- Idempotent: each insert is guarded by slug.

CREATE TEMP TABLE _worlds (name text PRIMARY KEY, schema_sql text, initial_sql text);

INSERT INTO _worlds VALUES
  ('fintech_wallet', 'CREATE TABLE users (
  user_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  district TEXT NOT NULL,
  joined_at DATE NOT NULL,
  kyc_verified BOOLEAN NOT NULL
);
CREATE TABLE agents (
  agent_id INT PRIMARY KEY,
  shop_name TEXT NOT NULL,
  district TEXT NOT NULL
);
CREATE TABLE transactions (
  txn_id INT PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(user_id),
  agent_id INT REFERENCES agents(agent_id),
  txn_type TEXT NOT NULL, -- ''cash_in'' | ''cash_out'' | ''send_money'' | ''payment''
  amount NUMERIC(12,2) NOT NULL,
  fee NUMERIC(10,2) NOT NULL DEFAULT 0,
  txn_at TIMESTAMP NOT NULL,
  status TEXT NOT NULL -- ''success'' | ''failed'' | ''reversed''
);', 'INSERT INTO users VALUES
  (1,''Rahim Uddin'',''Dhaka'',''2025-11-03'',true),
  (2,''Karima Akter'',''Chattogram'',''2025-12-18'',true),
  (3,''Sabbir Hossain'',''Dhaka'',''2026-01-25'',false),
  (4,''Nusrat Jahan'',''Sylhet'',''2026-02-07'',true),
  (5,''Tanvir Ahmed'',''Khulna'',''2026-02-19'',true),
  (6,''Mim Chowdhury'',''Dhaka'',''2026-03-12'',false),
  (7,''Arif Islam'',''Rajshahi'',''2026-04-02'',true),
  (8,''Farzana Haque'',''Chattogram'',''2026-04-28'',true);
INSERT INTO agents VALUES
  (101,''Bhai Bhai Telecom'',''Dhaka''),
  (102,''Ma Enterprise'',''Chattogram''),
  (103,''Padma Store'',''Rajshahi''),
  (104,''Digital Point'',''Dhaka'');
INSERT INTO transactions VALUES
  (1001,1,101,''cash_in'',5000.00,0,''2026-06-01 09:15:00'',''success''),
  (1002,1,NULL,''send_money'',1200.00,5.00,''2026-06-01 12:40:00'',''success''),
  (1003,2,102,''cash_in'',8000.00,0,''2026-06-02 10:05:00'',''success''),
  (1004,2,102,''cash_out'',3000.00,55.50,''2026-06-03 16:22:00'',''success''),
  (1005,3,101,''cash_in'',2000.00,0,''2026-06-03 18:30:00'',''success''),
  (1006,3,NULL,''payment'',450.00,0,''2026-06-04 11:00:00'',''success''),
  (1007,4,NULL,''send_money'',2500.00,10.00,''2026-06-04 14:45:00'',''failed''),
  (1008,4,NULL,''send_money'',2500.00,10.00,''2026-06-04 14:52:00'',''success''),
  (1009,5,104,''cash_in'',12000.00,0,''2026-06-05 09:00:00'',''success''),
  (1010,5,104,''cash_out'',7000.00,129.50,''2026-06-05 19:10:00'',''success''),
  (1011,1,NULL,''payment'',890.00,0,''2026-06-06 08:20:00'',''success''),
  (1012,6,101,''cash_in'',1500.00,0,''2026-06-06 13:33:00'',''success''),
  (1013,6,NULL,''send_money'',700.00,5.00,''2026-06-07 10:11:00'',''reversed''),
  (1014,7,103,''cash_in'',6000.00,0,''2026-06-07 15:55:00'',''success''),
  (1015,7,103,''cash_out'',2000.00,37.00,''2026-06-08 09:47:00'',''success''),
  (1016,8,102,''cash_in'',9500.00,0,''2026-06-08 11:28:00'',''success''),
  (1017,8,NULL,''payment'',1250.00,0,''2026-06-09 17:05:00'',''success''),
  (1018,2,NULL,''send_money'',4000.00,10.00,''2026-06-10 12:00:00'',''success''),
  (1019,5,NULL,''payment'',3200.00,0,''2026-06-10 20:15:00'',''success''),
  (1020,1,101,''cash_out'',2500.00,46.25,''2026-06-11 10:30:00'',''success''),
  (1021,4,102,''cash_in'',3000.00,0,''2026-06-11 14:00:00'',''success''),
  (1022,7,NULL,''send_money'',900.00,5.00,''2026-06-12 09:05:00'',''success''),
  (1023,8,102,''cash_out'',5000.00,92.50,''2026-06-12 18:40:00'',''failed''),
  (1024,8,102,''cash_out'',5000.00,92.50,''2026-06-12 18:47:00'',''success'');'),
  ('fintech_microloan', 'CREATE TABLE loans (
  loan_id INT PRIMARY KEY,
  borrower TEXT NOT NULL,
  district TEXT NOT NULL,
  principal NUMERIC(12,2) NOT NULL,
  disbursed_on DATE NOT NULL,
  term_months INT NOT NULL,
  status TEXT NOT NULL -- ''active'' | ''paid'' | ''defaulted''
);
CREATE TABLE repayments (
  repayment_id INT PRIMARY KEY,
  loan_id INT NOT NULL REFERENCES loans(loan_id),
  amount NUMERIC(10,2) NOT NULL,
  paid_on DATE NOT NULL
);', 'INSERT INTO loans VALUES
  (201,''Hasan Mahmud'',''Dhaka'',20000.00,''2026-01-10'',6,''active''),
  (202,''Ruma Begum'',''Chattogram'',15000.00,''2026-01-22'',6,''paid''),
  (203,''Sohel Rana'',''Dhaka'',30000.00,''2026-02-05'',12,''active''),
  (204,''Moriom Akter'',''Sylhet'',10000.00,''2026-02-18'',3,''paid''),
  (205,''Rasel Mia'',''Rajshahi'',25000.00,''2026-03-02'',12,''defaulted''),
  (206,''Shirin Sultana'',''Dhaka'',12000.00,''2026-03-15'',6,''active''),
  (207,''Jamal Uddin'',''Khulna'',18000.00,''2026-04-01'',6,''active''),
  (208,''Taslima Khatun'',''Chattogram'',8000.00,''2026-04-20'',3,''paid'');
INSERT INTO repayments VALUES
  (301,201,3500.00,''2026-02-10''),(302,201,3500.00,''2026-03-10''),
  (303,201,3500.00,''2026-04-12''),(304,202,2650.00,''2026-02-22''),
  (305,202,2650.00,''2026-03-20''),(306,202,2650.00,''2026-04-21''),
  (307,202,2650.00,''2026-05-19''),(308,202,2650.00,''2026-06-18''),
  (309,203,2800.00,''2026-03-05''),(310,203,2800.00,''2026-04-07''),
  (311,204,3450.00,''2026-03-18''),(312,204,3450.00,''2026-04-16''),
  (313,204,3450.00,''2026-05-18''),(314,205,2300.00,''2026-04-02''),
  (315,206,2150.00,''2026-04-15''),(316,206,2150.00,''2026-05-16''),
  (317,207,3200.00,''2026-05-01''),(318,207,3200.00,''2026-06-02''),
  (319,208,2750.00,''2026-05-20''),(320,208,2750.00,''2026-06-19'');'),
  ('ecommerce_shop', 'CREATE TABLE customers (
  customer_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  signup_date DATE NOT NULL
);
CREATE TABLE products (
  product_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC(10,2) NOT NULL
);
CREATE TABLE orders (
  order_id INT PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES customers(customer_id),
  order_date DATE NOT NULL,
  status TEXT NOT NULL -- ''delivered'' | ''cancelled'' | ''returned'' | ''processing''
);
CREATE TABLE order_items (
  order_id INT NOT NULL REFERENCES orders(order_id),
  product_id INT NOT NULL REFERENCES products(product_id),
  quantity INT NOT NULL,
  unit_price NUMERIC(10,2) NOT NULL,
  PRIMARY KEY (order_id, product_id)
);', 'INSERT INTO customers VALUES
  (1,''Shorna Rahman'',''Dhaka'',''2025-10-11''),
  (2,''Imran Kabir'',''Chattogram'',''2025-12-02''),
  (3,''Priya Das'',''Dhaka'',''2026-01-15''),
  (4,''Rakib Hasan'',''Sylhet'',''2026-02-20''),
  (5,''Lamia Islam'',''Khulna'',''2026-03-08''),
  (6,''Fahim Chowdhury'',''Dhaka'',''2026-04-19'');
INSERT INTO products VALUES
  (11,''Wireless Earbuds'',''Electronics'',2490.00),
  (12,''Cotton Panjabi'',''Fashion'',1850.00),
  (13,''Blender 500W'',''Home Appliance'',3200.00),
  (14,''Yoga Mat'',''Sports'',990.00),
  (15,''Power Bank 20000mAh'',''Electronics'',1750.00),
  (16,''Deshi Cotton Saree'',''Fashion'',2950.00),
  (17,''LED Desk Lamp'',''Home Appliance'',780.00),
  (18,''Gaming Mouse'',''Electronics'',1450.00);
INSERT INTO orders VALUES
  (501,1,''2026-05-02'',''delivered''),
  (502,2,''2026-05-04'',''delivered''),
  (503,1,''2026-05-10'',''returned''),
  (504,3,''2026-05-12'',''delivered''),
  (505,4,''2026-05-15'',''cancelled''),
  (506,5,''2026-05-18'',''delivered''),
  (507,3,''2026-05-21'',''delivered''),
  (508,6,''2026-05-25'',''processing''),
  (509,2,''2026-06-01'',''delivered''),
  (510,1,''2026-06-05'',''delivered'');
INSERT INTO order_items VALUES
  (501,11,1,2490.00),(501,14,2,990.00),
  (502,12,1,1850.00),
  (503,13,1,3200.00),
  (504,15,2,1750.00),(504,17,1,780.00),
  (505,16,1,2950.00),
  (506,11,1,2490.00),(506,15,1,1750.00),
  (507,14,1,990.00),(507,17,2,780.00),
  (508,13,1,3200.00),
  (509,16,2,2950.00),(509,12,1,1850.00),
  (510,15,1,1750.00);'),
  ('logistics_courier', 'CREATE TABLE hubs (
  hub_id INT PRIMARY KEY,
  city TEXT NOT NULL
);
CREATE TABLE riders (
  rider_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  hub_id INT NOT NULL REFERENCES hubs(hub_id)
);
CREATE TABLE parcels (
  parcel_id INT PRIMARY KEY,
  sender_area TEXT NOT NULL,
  receiver_area TEXT NOT NULL,
  weight_kg NUMERIC(6,2) NOT NULL,
  cod_amount NUMERIC(10,2) NOT NULL, -- cash on delivery, 0 = prepaid
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE deliveries (
  delivery_id INT PRIMARY KEY,
  parcel_id INT NOT NULL REFERENCES parcels(parcel_id),
  rider_id INT NOT NULL REFERENCES riders(rider_id),
  picked_at TIMESTAMP NOT NULL,
  delivered_at TIMESTAMP, -- NULL = not delivered yet
  status TEXT NOT NULL -- ''delivered'' | ''in_transit'' | ''failed''
);', 'INSERT INTO hubs VALUES (1,''Dhaka''),(2,''Chattogram''),(3,''Sylhet'');
INSERT INTO riders VALUES
  (21,''Jashim Uddin'',1),(22,''Selim Reza'',1),(23,''Polash Mia'',2),
  (24,''Hridoy Khan'',2),(25,''Shuvo Roy'',3);
INSERT INTO parcels VALUES
  (301,''Uttara'',''Dhanmondi'',1.20,1500.00,''2026-06-01 08:00:00''),
  (302,''Banani'',''Mirpur'',0.50,0,''2026-06-01 09:30:00''),
  (303,''Agrabad'',''Nasirabad'',2.80,3200.00,''2026-06-01 10:15:00''),
  (304,''Gulshan'',''Uttara'',0.90,850.00,''2026-06-02 08:45:00''),
  (305,''Zindabazar'',''Ambarkhana'',1.50,2100.00,''2026-06-02 11:20:00''),
  (306,''Dhanmondi'',''Banani'',3.40,0,''2026-06-03 09:00:00''),
  (307,''Mirpur'',''Gulshan'',0.75,650.00,''2026-06-03 14:30:00''),
  (308,''Nasirabad'',''Agrabad'',1.10,1200.00,''2026-06-04 10:00:00''),
  (309,''Uttara'',''Mirpur'',2.00,1800.00,''2026-06-04 15:45:00''),
  (310,''Ambarkhana'',''Zindabazar'',0.60,0,''2026-06-05 09:10:00'');
INSERT INTO deliveries VALUES
  (401,301,21,''2026-06-01 10:00:00'',''2026-06-01 15:30:00'',''delivered''),
  (402,302,22,''2026-06-01 11:00:00'',''2026-06-01 13:45:00'',''delivered''),
  (403,303,23,''2026-06-01 12:30:00'',''2026-06-02 17:00:00'',''delivered''),
  (404,304,21,''2026-06-02 10:30:00'',''2026-06-02 14:20:00'',''delivered''),
  (405,305,25,''2026-06-02 13:00:00'',NULL,''in_transit''),
  (406,306,22,''2026-06-03 11:00:00'',''2026-06-04 10:30:00'',''delivered''),
  (407,307,21,''2026-06-03 16:00:00'',NULL,''failed''),
  (408,307,22,''2026-06-04 09:00:00'',''2026-06-04 12:15:00'',''delivered''),
  (409,308,24,''2026-06-04 11:30:00'',''2026-06-04 18:40:00'',''delivered''),
  (410,309,21,''2026-06-05 08:30:00'',NULL,''in_transit''),
  (411,310,25,''2026-06-05 10:00:00'',''2026-06-05 12:00:00'',''delivered'');'),
  ('telco_network', 'CREATE TABLE plans (
  plan_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  monthly_fee NUMERIC(8,2) NOT NULL,
  data_gb INT NOT NULL
);
CREATE TABLE subscribers (
  sub_id INT PRIMARY KEY,
  name TEXT NOT NULL,
  plan_id INT NOT NULL REFERENCES plans(plan_id),
  activated_on DATE NOT NULL,
  district TEXT NOT NULL
);
CREATE TABLE recharges (
  recharge_id INT PRIMARY KEY,
  sub_id INT NOT NULL REFERENCES subscribers(sub_id),
  amount NUMERIC(8,2) NOT NULL,
  recharged_at TIMESTAMP NOT NULL
);
CREATE TABLE usage_daily (
  sub_id INT NOT NULL REFERENCES subscribers(sub_id),
  usage_date DATE NOT NULL,
  data_mb INT NOT NULL,
  voice_min INT NOT NULL,
  PRIMARY KEY (sub_id, usage_date)
);', 'INSERT INTO plans VALUES
  (1,''Bondhu 199'',199.00,5),(2,''Shadhin 349'',349.00,15),
  (3,''Power 599'',599.00,40),(4,''Business 999'',999.00,100);
INSERT INTO subscribers VALUES
  (61,''Mahmud Hasan'',1,''2025-09-14'',''Dhaka''),
  (62,''Rima Sultana'',2,''2025-11-30'',''Chattogram''),
  (63,''Joy Barua'',2,''2026-01-08'',''Chattogram''),
  (64,''Sadia Afrin'',3,''2026-02-14'',''Dhaka''),
  (65,''Nayeem Islam'',1,''2026-03-22'',''Rajshahi''),
  (66,''Tania Akter'',4,''2026-04-05'',''Dhaka'');
INSERT INTO recharges VALUES
  (901,61,199.00,''2026-06-01 08:00:00''),
  (902,62,349.00,''2026-06-01 09:30:00''),
  (903,63,100.00,''2026-06-02 12:00:00''),
  (904,63,249.00,''2026-06-03 10:15:00''),
  (905,64,599.00,''2026-06-03 18:20:00''),
  (906,65,199.00,''2026-06-04 11:00:00''),
  (907,66,999.00,''2026-06-05 09:45:00''),
  (908,61,50.00,''2026-06-08 20:30:00''),
  (909,62,100.00,''2026-06-10 14:10:00'');
INSERT INTO usage_daily VALUES
  (61,''2026-06-01'',350,22),(61,''2026-06-02'',420,15),(61,''2026-06-03'',180,40),
  (62,''2026-06-01'',900,10),(62,''2026-06-02'',1150,8),(62,''2026-06-03'',600,25),
  (63,''2026-06-01'',450,30),(63,''2026-06-02'',380,45),(63,''2026-06-03'',720,12),
  (64,''2026-06-01'',2100,5),(64,''2026-06-02'',1800,18),(64,''2026-06-03'',2500,7),
  (65,''2026-06-01'',120,60),(65,''2026-06-02'',90,75),(65,''2026-06-03'',200,55),
  (66,''2026-06-01'',3400,20),(66,''2026-06-02'',4100,35),(66,''2026-06-03'',2900,28);');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'app-only-transactions', 'App-Only Transactions', 'code', 'Easy', 'Fintech',
       'NULL Handling', ARRAY['is-null']::text[], 'Digital adoption tracking: return `txn_id`, `user_id`, and `txn_type` of transactions done **without an agent** (no agent involved), newest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT txn_id, user_id, txn_type FROM transactions WHERE agent_id IS NULL ORDER BY txn_at DESC;',
       '["App-only means agent_id IS NULL","Never write = NULL"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 77
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'app-only-transactions');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'dhaka-agents', 'Agent Points in Dhaka', 'code', 'Easy', 'Fintech',
       'Filtering', ARRAY['where']::text[], 'Field ops is visiting Dhaka agent points today. Return `agent_id` and `shop_name` of agents in the Dhaka district, alphabetical by shop name.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT agent_id, shop_name FROM agents WHERE district = ''Dhaka'' ORDER BY shop_name;',
       '["Filter agents by district","ORDER BY shop_name"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 88
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'dhaka-agents');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'fee-revenue-by-type', 'Fee Revenue by Transaction Type', 'code', 'Easy', 'Fintech',
       'Aggregation', ARRAY['sum','group-by']::text[], 'Fees are the business. For successful transactions, return each `txn_type` and total `fee_revenue`, highest first. Skip types that earned nothing.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT txn_type, SUM(fee) AS fee_revenue
FROM transactions WHERE status = ''success''
GROUP BY txn_type HAVING SUM(fee) > 0 ORDER BY fee_revenue DESC;',
       '["SUM(fee) per type","HAVING SUM(fee) > 0 drops zero-fee types"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 68
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'fee-revenue-by-type');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'unverified-active-users', 'Unverified but Transacting', 'code', 'Medium', 'Fintech',
       'Joins', ARRAY['join','distinct']::text[], 'Compliance red flag: users who are **not KYC-verified** yet have successful transactions. Return each such user''s `user_id` and `name` once, ordered by user_id.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT DISTINCT u.user_id, u.name
FROM users u JOIN transactions t ON t.user_id = u.user_id
WHERE u.kyc_verified = false AND t.status = ''success''
ORDER BY u.user_id;',
       '["Join and filter kyc_verified = false","DISTINCT prevents one row per transaction"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 63
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'unverified-active-users');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'avg-txn-size-by-district', 'Average Ticket Size by District', 'code', 'Medium', 'Fintech',
       'Aggregation', ARRAY['avg','join','round']::text[], 'Marketing segments districts by ticket size. Return user `district` and the average successful transaction `amount` (`avg_amount`, 2 decimals), highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT u.district, ROUND(AVG(t.amount), 2) AS avg_amount
FROM users u JOIN transactions t ON t.user_id = u.user_id
WHERE t.status = ''success''
GROUP BY u.district ORDER BY avg_amount DESC;',
       '["District lives on users","ROUND(AVG(amount), 2)"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 60
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'avg-txn-size-by-district');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'first-transaction-per-user', 'Each User''s First Transaction', 'code', 'Medium', 'Fintech',
       'Window Functions', ARRAY['row-number','first-event']::text[], 'Onboarding analysis: what do users do first? Return `user_id`, `txn_type`, and `txn_at` of each user''s **earliest** transaction, ordered by user_id.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT user_id, txn_type, txn_at FROM (
  SELECT user_id, txn_type, txn_at,
         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY txn_at) AS rn
  FROM transactions
) t WHERE rn = 1 ORDER BY user_id;',
       '["ROW_NUMBER() ordered by txn_at ascending","Keep rn = 1"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 52
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'first-transaction-per-user');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'share-of-volume-by-type', 'Each Type''s Share of Volume', 'code', 'Hard', 'Fintech',
       'Window Functions', ARRAY['window','ratio']::text[], 'The exec deck wants percentages, not raw sums. For successful transactions, return `txn_type`, `type_volume`, and `pct_share` of total volume (1 decimal), highest share first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT txn_type, SUM(amount) AS type_volume,
       ROUND(100.0 * SUM(amount) / SUM(SUM(amount)) OVER (), 1) AS pct_share
FROM transactions WHERE status = ''success''
GROUP BY txn_type ORDER BY pct_share DESC;',
       '["SUM(SUM(amount)) OVER () gives the grand total next to each group","Multiply by 100.0 for float math","ROUND(x, 1)"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 33
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'share-of-volume-by-type');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'loan-book-by-status', 'Loan Book by Status', 'code', 'Easy', 'Fintech',
       'Aggregation', ARRAY['group-by','sum']::text[], 'Portfolio snapshot: return each loan `status`, the number of loans (`loan_count`), and total `principal_total`, ordered by principal_total descending.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT status, COUNT(*) AS loan_count, SUM(principal) AS principal_total
FROM loans GROUP BY status ORDER BY principal_total DESC;',
       '["One GROUP BY, two aggregates","COUNT(*) and SUM(principal)"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 79
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'loan-book-by-status');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'repayment-progress', 'Repayment Progress per Loan', 'code', 'Medium', 'Fintech',
       'Joins', ARRAY['join','group-by','ratio']::text[], 'Collections tracks recovery. For each loan with repayments, return `loan_id`, `borrower`, `principal`, total repaid (`repaid`), and `pct_recovered` (repaid ÷ principal × 100, 1 decimal), least recovered first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT l.loan_id, l.borrower, l.principal, SUM(r.amount) AS repaid,
       ROUND(100.0 * SUM(r.amount) / l.principal, 1) AS pct_recovered
FROM loans l JOIN repayments r ON r.loan_id = l.loan_id
GROUP BY l.loan_id, l.borrower, l.principal
ORDER BY pct_recovered;',
       '["SUM repayments per loan","Percentage = 100.0 * repaid / principal","Order ascending to surface laggards"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 55
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'repayment-progress');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'no-repayment-in-may', 'Loans Silent in May', 'code', 'Medium', 'Fintech',
       'Subqueries', ARRAY['not-exists','date']::text[], 'A loan with no repayment in May 2026 gets a follow-up call. Return `loan_id`, `borrower`, and `status` of **active or defaulted** loans that made no repayment in May 2026, by loan_id.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT l.loan_id, l.borrower, l.status
FROM loans l
WHERE l.status IN (''active'',''defaulted'')
  AND NOT EXISTS (
    SELECT 1 FROM repayments r
    WHERE r.loan_id = l.loan_id
      AND r.paid_on >= ''2026-05-01'' AND r.paid_on < ''2026-06-01''
  )
ORDER BY l.loan_id;',
       '["NOT EXISTS with a date-bounded subquery","Half-open May range","Filter status first"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 48
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'no-repayment-in-may');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'monthly-collections', 'Monthly Collections Trend', 'code', 'Medium', 'Fintech',
       'Date Functions', ARRAY['date-trunc','group-by']::text[], 'Finance charts collections by month. Return each month (`month`, as the first day of the month) and total repayments received (`collected`), in time order.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT DATE_TRUNC(''month'', paid_on)::date AS month, SUM(amount) AS collected
FROM repayments GROUP BY DATE_TRUNC(''month'', paid_on) ORDER BY month;',
       '["DATE_TRUNC(''month'', paid_on)","Cast to ::date for a clean label"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 57
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'monthly-collections');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'gap-between-repayments', 'Gaps Between Repayments', 'code', 'Hard', 'Fintech',
       'Window Functions', ARRAY['lag','date-diff']::text[], 'Late-payment early warning: for each repayment after a loan''s first, compute the days since that loan''s **previous** repayment. Return `loan_id`, `paid_on`, and `days_since_prev`, largest gap first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT loan_id, paid_on, paid_on - prev_paid AS days_since_prev FROM (
  SELECT loan_id, paid_on, LAG(paid_on) OVER (PARTITION BY loan_id ORDER BY paid_on) AS prev_paid
  FROM repayments
) t WHERE prev_paid IS NOT NULL
ORDER BY days_since_prev DESC;',
       '["LAG(paid_on) partitioned by loan","Date minus date is an integer day count in Postgres","Drop each loan''s first repayment (prev IS NULL)"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 31
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'gap-between-repayments');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'district-default-rate', 'Default Rate by District', 'code', 'Hard', 'Fintech',
       'Conditional Aggregation', ARRAY['case-when','ratio']::text[], 'Credit policy wants geography risk. Return each `district`, its `total_loans`, `defaulted_loans`, and `default_rate_pct` (share of loans defaulted, 1 decimal), highest rate first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT district, COUNT(*) AS total_loans,
       COUNT(*) FILTER (WHERE status = ''defaulted'') AS defaulted_loans,
       ROUND(100.0 * COUNT(*) FILTER (WHERE status = ''defaulted'') / COUNT(*), 1) AS default_rate_pct
FROM loans GROUP BY district ORDER BY default_rate_pct DESC;',
       '["COUNT(*) FILTER (WHERE ...) counts a subset","Rate = 100.0 * defaulted / total","GROUP BY district"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 35
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'district-default-rate');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-filter-vs-case-count', 'Counting a Subset Inside GROUP BY', 'mcq', 'Medium', 'Fintech',
       'Conditional Aggregation', ARRAY['concept']::text[], 'You''re counting defaulted loans per district inside a single GROUP BY query. Which two expressions are equivalent ways to do it?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"COUNT(*) FILTER (WHERE status=''defaulted'') and SUM(CASE WHEN status=''defaulted'' THEN 1 ELSE 0 END)"},{"label":"B","text":"COUNT(status=''defaulted'') and SUM(status)"},{"label":"C","text":"COUNT(DISTINCT status) and MAX(status)"},{"label":"D","text":"WHERE status=''defaulted'' twice"}]'::jsonb, 'A',
       NULL, 0, NULL, 58
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-filter-vs-case-count');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-union-vs-union-all', 'UNION vs UNION ALL', 'mcq', 'Easy', 'Fintech',
       'Set Operations', ARRAY['concept']::text[], 'You combine June''s agent list with July''s agent list; the same agent can appear in both months and you want it **once**.

Which operator, and why?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"UNION ALL — it''s faster"},{"label":"B","text":"UNION — it removes duplicate rows across the combined result"},{"label":"C","text":"INTERSECT — it merges the lists"},{"label":"D","text":"EXCEPT — it keeps the shared agents"}]'::jsonb, 'B',
       NULL, 0, NULL, 70
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-union-vs-union-all');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-fee-avg-null', 'Does AVG See NULLs?', 'mcq', 'Medium', 'Fintech',
       'NULL Semantics', ARRAY['avg','null']::text[], 'A fee column has values 10, 20, and NULL.

What is `AVG(fee)` over those three rows?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"10 — NULL counts as zero"},{"label":"B","text":"15 — AVG ignores NULLs (30 / 2)"},{"label":"C","text":"NULL — one NULL poisons the aggregate"},{"label":"D","text":"An error"}]'::jsonb, 'B',
       NULL, 0, NULL, 61
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-fee-avg-null');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-between-inclusive', 'Is BETWEEN Inclusive?', 'mcq', 'Easy', 'Fintech',
       'Filtering', ARRAY['between']::text[], '`WHERE amount BETWEEN 1000 AND 5000` — which amounts qualify?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"Strictly greater than 1000 and strictly less than 5000"},{"label":"B","text":"1000 and 5000 are both included"},{"label":"C","text":"1000 included, 5000 excluded"},{"label":"D","text":"Depends on the database collation"}]'::jsonb, 'B',
       NULL, 0, NULL, 76
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-between-inclusive');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-window-vs-groupby', 'Window Function vs GROUP BY', 'mcq', 'Medium', 'Fintech',
       'Window Functions', ARRAY['concept']::text[], 'You need every transaction row **plus** each user''s total alongside it.

Why is `SUM(amount) OVER (PARTITION BY user_id)` the right tool rather than GROUP BY?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"GROUP BY would collapse rows; a window function keeps every row and adds the aggregate"},{"label":"B","text":"Window functions are always faster than GROUP BY"},{"label":"C","text":"GROUP BY cannot compute SUM"},{"label":"D","text":"They are interchangeable; it''s a style choice"}]'::jsonb, 'A',
       NULL, 0, NULL, 59
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-window-vs-groupby');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'collections-priority-list', 'Case: Monday Collections Priority List', 'case_study', 'Medium', 'Fintech',
       'Joins', ARRAY['left-join','coalesce']::text[], '**Scenario.** The collections team starts Monday with a priority list: every non-paid loan and how much is still outstanding.

For loans not in `paid` status, return `loan_id`, `borrower`, `district`, and `outstanding` (principal minus total repaid; loans with zero repayments count fully outstanding), largest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT l.loan_id, l.borrower, l.district,
       l.principal - COALESCE(SUM(r.amount), 0) AS outstanding
FROM loans l LEFT JOIN repayments r ON r.loan_id = l.loan_id
WHERE l.status <> ''paid''
GROUP BY l.loan_id, l.borrower, l.district, l.principal
ORDER BY outstanding DESC;',
       '["LEFT JOIN keeps loans with no repayments","COALESCE(SUM(amount), 0) turns no-repayment NULL into 0","Outstanding = principal - repaid"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 49
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'collections-priority-list');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'agent-inactivity-audit', 'Case: Agent Inactivity Audit', 'case_study', 'Hard', 'Fintech',
       'Subqueries', ARRAY['anti-join','date']::text[], '**Scenario.** Distribution audits agent points every quarter; an agent with no successful transaction after **8 June 2026** is flagged dormant.

Return `agent_id` and `shop_name` of dormant agents, with their last successful activity date (`last_active`, NULL if never active), oldest activity first (NULLs first).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_wallet'), ''), 'SELECT a.agent_id, a.shop_name, MAX(t.txn_at)::date AS last_active
FROM agents a LEFT JOIN transactions t
  ON t.agent_id = a.agent_id AND t.status = ''success''
GROUP BY a.agent_id, a.shop_name
HAVING COALESCE(MAX(t.txn_at), ''1970-01-01'') < ''2026-06-08''
ORDER BY last_active NULLS FIRST;',
       '["Put the status filter in the JOIN condition so agents with no activity survive","MAX(txn_at) is the last activity; HAVING applies the cutoff","COALESCE handles never-active agents"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 30
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'agent-inactivity-audit');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mission-collections-sprint', 'Mission: The Collections Sprint', 'root', 'Medium', 'Fintech',
       'Investigation', ARRAY['mission','lending']::text[], '**The story.** Quarter-end is two weeks away and your DFS lender''s recovery number looks soft. The head of credit hands you the microloan book: "Tell me exactly where the money is stuck, and who we call first." Four steps, one dataset, increasingly sharp answers.',
       '', '', '',
       '[]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 44
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mission-collections-sprint');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'fashion-under-2500', 'Affordable Fashion Picks', 'code', 'Easy', 'E-Commerce',
       'Filtering', ARRAY['where','and']::text[], 'The "Fashion under ৳2,500" carousel needs data. Return `name` and `price` of Fashion products priced below ৳2,500, cheapest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT name, price FROM products WHERE category = ''Fashion'' AND price < 2500 ORDER BY price;',
       '["Two conditions with AND","Cheapest first = ORDER BY price"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 87
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'fashion-under-2500');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'customers-from-dhaka', 'Dhaka Customer Base', 'code', 'Easy', 'E-Commerce',
       'Filtering', ARRAY['where','date']::text[], 'Return `name` and `signup_date` of customers in Dhaka who signed up in 2026, newest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT name, signup_date FROM customers
WHERE city = ''Dhaka'' AND signup_date >= ''2026-01-01''
ORDER BY signup_date DESC;',
       '["City filter plus a date lower bound","All 2026 dates are >= ''2026-01-01''"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 84
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'customers-from-dhaka');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'order-count-per-customer', 'Orders per Customer', 'code', 'Easy', 'E-Commerce',
       'Joins', ARRAY['join','count']::text[], 'Return each customer `name` and their total order count (`orders_count`) — any status — most orders first, then by name.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT c.name, COUNT(o.order_id) AS orders_count
FROM customers c JOIN orders o ON o.customer_id = c.customer_id
GROUP BY c.name ORDER BY orders_count DESC, name;',
       '["Join orders to customers","COUNT per customer"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 80
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'order-count-per-customer');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'category-price-stats', 'Price Stats per Category', 'code', 'Medium', 'E-Commerce',
       'Aggregation', ARRAY['min-max','avg']::text[], 'Pricing reviews start from the spread. Return each `category` with its cheapest (`min_price`), most expensive (`max_price`), and average (`avg_price`, 2 decimals) product price, alphabetical by category.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT category, MIN(price) AS min_price, MAX(price) AS max_price, ROUND(AVG(price), 2) AS avg_price
FROM products GROUP BY category ORDER BY category;',
       '["Three aggregates in one GROUP BY","ROUND the average only"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 72
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'category-price-stats');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'cancelled-or-returned-value', 'Value Lost to Cancellations and Returns', 'code', 'Medium', 'E-Commerce',
       'Filtering', ARRAY['in','join']::text[], 'Sum the item value of orders that were **cancelled or returned**. Return one row: `lost_value`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT SUM(oi.quantity * oi.unit_price) AS lost_value
FROM orders o JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status IN (''cancelled'',''returned'');',
       '["status IN (...) covers both","Value = quantity * unit_price"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 69
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'cancelled-or-returned-value');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'multi-item-orders', 'Orders with Multiple Line Items', 'code', 'Medium', 'E-Commerce',
       'Aggregation', ARRAY['having','count']::text[], 'Bundling analysis: which orders contained **more than one distinct product**? Return `order_id` and `item_lines`, most lines first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT order_id, COUNT(*) AS item_lines
FROM order_items GROUP BY order_id
HAVING COUNT(*) > 1 ORDER BY item_lines DESC, order_id;',
       '["Each order_items row is one product line","HAVING COUNT(*) > 1"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 67
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'multi-item-orders');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'june-vs-may-revenue', 'May vs June Delivered Revenue', 'code', 'Medium', 'E-Commerce',
       'Conditional Aggregation', ARRAY['case-when','date']::text[], 'One row, two numbers: delivered revenue in **May 2026** (`may_revenue`) and in **June 2026** (`june_revenue`).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT
  SUM(CASE WHEN o.order_date >= ''2026-05-01'' AND o.order_date < ''2026-06-01'' THEN oi.quantity * oi.unit_price ELSE 0 END) AS may_revenue,
  SUM(CASE WHEN o.order_date >= ''2026-06-01'' AND o.order_date < ''2026-07-01'' THEN oi.quantity * oi.unit_price ELSE 0 END) AS june_revenue
FROM orders o JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status = ''delivered'';',
       '["Pivot the months with CASE inside SUM","Keep the delivered filter in WHERE"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 54
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'june-vs-may-revenue');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'products-in-every-status', 'Products Sold and Also Returned', 'code', 'Medium', 'E-Commerce',
       'Set Operations', ARRAY['intersect','subquery']::text[], 'Quality wants products that appear in **both** a delivered order and a cancelled order — sold fine to some, abandoned by others. Return their `product_id` and `name`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT p.product_id, p.name FROM products p
WHERE p.product_id IN (
  SELECT oi.product_id FROM order_items oi JOIN orders o ON o.order_id = oi.order_id WHERE o.status = ''delivered''
)
AND p.product_id IN (
  SELECT oi.product_id FROM order_items oi JOIN orders o ON o.order_id = oi.order_id WHERE o.status = ''cancelled''
);',
       '["Two membership tests, one per status","IN (subquery) twice — or INTERSECT two selects"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 50
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'products-in-every-status');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'revenue-rank-in-category', 'Revenue Rank Within Category', 'code', 'Hard', 'E-Commerce',
       'Window Functions', ARRAY['rank','partition']::text[], 'For **delivered** sales, rank products **within their category** by revenue. Return `category`, `name`, `revenue`, and `rank_in_category`, ordered by category then rank.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT category, name, revenue,
       RANK() OVER (PARTITION BY category ORDER BY revenue DESC) AS rank_in_category
FROM (
  SELECT p.category, p.name, SUM(oi.quantity * oi.unit_price) AS revenue
  FROM products p
  JOIN order_items oi ON oi.product_id = p.product_id
  JOIN orders o ON o.order_id = oi.order_id
  WHERE o.status = ''delivered''
  GROUP BY p.category, p.name
) t ORDER BY category, rank_in_category;',
       '["Aggregate revenue per product first","RANK() partitioned by category over that","Two-level query"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 34
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'revenue-rank-in-category');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'days-to-first-order', 'Days from Signup to First Order', 'code', 'Hard', 'E-Commerce',
       'Window Functions', ARRAY['min','date-diff']::text[], 'Activation metric: for every customer who ordered, return `name`, `signup_date`, their first order date (`first_order`), and `days_to_activate`, fastest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT c.name, c.signup_date, MIN(o.order_date) AS first_order,
       MIN(o.order_date) - c.signup_date AS days_to_activate
FROM customers c JOIN orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name, c.signup_date
ORDER BY days_to_activate;',
       '["MIN(order_date) is the first order","Date subtraction yields days","Group per customer"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 42
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'days-to-first-order');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'aov-by-city', 'Average Order Value by City', 'code', 'Hard', 'E-Commerce',
       'Subqueries', ARRAY['cte','avg']::text[], 'City economics: average **delivered** order value per customer city (`aov`, 2 decimals), highest first. (Average of order totals — not the total divided by item count.)',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'WITH order_values AS (
  SELECT o.order_id, c.city, SUM(oi.quantity * oi.unit_price) AS order_value
  FROM orders o
  JOIN customers c ON c.customer_id = o.customer_id
  JOIN order_items oi ON oi.order_id = o.order_id
  WHERE o.status = ''delivered''
  GROUP BY o.order_id, c.city
)
SELECT city, ROUND(AVG(order_value), 2) AS aov
FROM order_values GROUP BY city ORDER BY aov DESC;',
       '["Order value first (per order), city average second","A CTE keeps the two levels readable"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 37
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'aov-by-city');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-inner-join-drops', 'Who Disappears in an INNER JOIN?', 'mcq', 'Easy', 'E-Commerce',
       'Joins', ARRAY['concept']::text[], '`customers INNER JOIN orders` — customer 4''s only order was cancelled and customer 6''s order is processing, but one registered customer has **no orders at all**.

What happens to that no-order customer in the join result?',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), '',
       '[]'::jsonb, '[{"label":"A","text":"They appear with NULL order columns"},{"label":"B","text":"They are excluded — INNER JOIN keeps only matching rows"},{"label":"C","text":"They appear once with default values"},{"label":"D","text":"The query errors"}]'::jsonb, 'B',
       NULL, 0, NULL, 78
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-inner-join-drops');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-group-by-rule', 'The GROUP BY Column Rule', 'mcq', 'Easy', 'E-Commerce',
       'Aggregation', ARRAY['concept']::text[], '`SELECT city, name, COUNT(*) FROM customers GROUP BY city;` fails in Postgres.

Why?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"COUNT(*) can''t be combined with text columns"},{"label":"B","text":"name is neither grouped nor aggregated, so its value per group is ambiguous"},{"label":"C","text":"GROUP BY only accepts one column"},{"label":"D","text":"city must appear last in the SELECT list"}]'::jsonb, 'B',
       NULL, 0, NULL, 69
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-group-by-rule');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-limit-without-order', 'LIMIT Without ORDER BY', 'mcq', 'Medium', 'E-Commerce',
       'Sorting', ARRAY['concept','limit']::text[], 'A dashboard uses `SELECT * FROM orders LIMIT 5` to show "the latest 5 orders" — and sometimes shows different rows after a deploy.

What''s the root cause?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"LIMIT is non-deterministic without ORDER BY — row order is not guaranteed"},{"label":"B","text":"LIMIT caches results between deploys"},{"label":"C","text":"Postgres returns rows by primary key unless told otherwise"},{"label":"D","text":"The table needs VACUUM"}]'::jsonb, 'A',
       NULL, 0, NULL, 63
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-limit-without-order');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-left-join-count-trap', 'The LEFT JOIN COUNT(*) Trap', 'mcq', 'Medium', 'E-Commerce',
       'Joins', ARRAY['count','null']::text[], 'Counting orders per customer with `customers LEFT JOIN orders`: a customer with **zero orders** shows a count of 1 when you use `COUNT(*)`.

What fixes it?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"Switch to COUNT(o.order_id) — it ignores the NULL from the unmatched row"},{"label":"B","text":"Use INNER JOIN instead"},{"label":"C","text":"Add DISTINCT to COUNT(*)"},{"label":"D","text":"Filter WHERE o.order_id IS NOT NULL"}]'::jsonb, 'A',
       NULL, 0, NULL, 55
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-left-join-count-trap');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-subquery-in-where', 'Scalar Subquery Cardinality', 'mcq', 'Medium', 'E-Commerce',
       'Subqueries', ARRAY['concept']::text[], '`WHERE price > (SELECT AVG(price) FROM products)` works, but `WHERE price > (SELECT price FROM products)` errors at runtime.

Why?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"AVG is the only function allowed in subqueries"},{"label":"B","text":"A comparison needs a scalar; the second subquery returns multiple rows"},{"label":"C","text":"The second subquery is missing GROUP BY"},{"label":"D","text":"Subqueries in WHERE must use IN"}]'::jsonb, 'B',
       NULL, 0, NULL, 60
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-subquery-in-where');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'free-shipping-threshold', 'Case: Setting the Free-Shipping Threshold', 'case_study', 'Medium', 'E-Commerce',
       'Aggregation', ARRAY['percentile','order-value']::text[], '**Scenario.** Growth wants free shipping above a threshold that most orders *almost* reach. As the first input, they need every delivered order''s value and how it compares to the average.

Return `order_id`, `order_value`, and `vs_avg` (order value minus the average delivered order value, 2 decimals), highest value first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'WITH vals AS (
  SELECT o.order_id, SUM(oi.quantity * oi.unit_price) AS order_value
  FROM orders o JOIN order_items oi ON oi.order_id = o.order_id
  WHERE o.status = ''delivered''
  GROUP BY o.order_id
)
SELECT order_id, order_value, ROUND(order_value - AVG(order_value) OVER (), 2) AS vs_avg
FROM vals ORDER BY order_value DESC;',
       '["Per-order values in a CTE","AVG(...) OVER () compares each row to the overall average without collapsing rows"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 43
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'free-shipping-threshold');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'category-return-rate', 'Case: Category Return Rates', 'case_study', 'Hard', 'E-Commerce',
       'Conditional Aggregation', ARRAY['ratio','case-when']::text[], '**Scenario.** Supplier scorecards need a defect proxy: of each category''s ordered units (delivered + returned orders only), what share sat in returned orders?

Return `category`, `units_total`, `units_returned`, and `return_rate_pct` (1 decimal), highest rate first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'ecommerce_shop'), ''), 'SELECT p.category,
       SUM(oi.quantity) AS units_total,
       SUM(CASE WHEN o.status = ''returned'' THEN oi.quantity ELSE 0 END) AS units_returned,
       ROUND(100.0 * SUM(CASE WHEN o.status = ''returned'' THEN oi.quantity ELSE 0 END) / SUM(oi.quantity), 1) AS return_rate_pct
FROM products p
JOIN order_items oi ON oi.product_id = p.product_id
JOIN orders o ON o.order_id = oi.order_id
WHERE o.status IN (''delivered'',''returned'')
GROUP BY p.category
ORDER BY return_rate_pct DESC;',
       '["Restrict to the two statuses in WHERE","Returned units via conditional SUM","Rate = returned / total units"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 32
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'category-return-rate');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'prepaid-parcels', 'Prepaid Parcels', 'code', 'Easy', 'Logistics',
       'Filtering', ARRAY['where']::text[], 'Prepaid parcels (no COD to collect) skip the cash desk. Return `parcel_id`, `sender_area`, and `receiver_area` of parcels with zero COD, by parcel_id.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT parcel_id, sender_area, receiver_area FROM parcels WHERE cod_amount = 0 ORDER BY parcel_id;',
       '["cod_amount = 0 means prepaid","ORDER BY parcel_id for a stable list"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 89
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'prepaid-parcels');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'heavy-parcels', 'Heavy Parcel Surcharge List', 'code', 'Easy', 'Logistics',
       'Filtering', ARRAY['where','order-by']::text[], 'Parcels over 2 kg carry a surcharge. Return `parcel_id`, `weight_kg`, and `receiver_area`, heaviest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT parcel_id, weight_kg, receiver_area FROM parcels WHERE weight_kg > 2 ORDER BY weight_kg DESC;',
       '["Numeric comparison on weight_kg","Heaviest first = ORDER BY weight_kg DESC"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 90
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'heavy-parcels');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'deliveries-per-rider', 'Completed Deliveries per Rider', 'code', 'Easy', 'Logistics',
       'Joins', ARRAY['join','count']::text[], 'Weekly leaderboard: return rider `name` and their **delivered** count (`completed`), highest first, then by name.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT r.name, COUNT(*) AS completed
FROM riders r JOIN deliveries d ON d.rider_id = r.rider_id
WHERE d.status = ''delivered''
GROUP BY r.name ORDER BY completed DESC, name;',
       '["Filter delivered, then count per rider","Tie-break the order with the rider name"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 81
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'deliveries-per-rider');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'hub-delivery-share', 'Delivery Share by Hub', 'code', 'Medium', 'Logistics',
       'Joins', ARRAY['multi-join','group-by']::text[], 'Which hub moves the network? Return hub `city` and its count of **delivered** runs (`delivered_count`), highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT h.city, COUNT(*) AS delivered_count
FROM hubs h
JOIN riders r ON r.hub_id = h.hub_id
JOIN deliveries d ON d.rider_id = r.rider_id
WHERE d.status = ''delivered''
GROUP BY h.city ORDER BY delivered_count DESC;',
       '["Hubs connect to deliveries through riders","Two joins"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 66
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'hub-delivery-share');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'same-day-deliveries', 'Same-Day Delivery Rate Inputs', 'code', 'Medium', 'Logistics',
       'Date Functions', ARRAY['date','case']::text[], 'The SLA team defines *same-day* as picked and delivered on the same calendar date. Return `delivery_id`, `parcel_id`, and `same_day` (true/false) for every **delivered** run, delivery_id order.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT delivery_id, parcel_id, (picked_at::date = delivered_at::date) AS same_day
FROM deliveries WHERE status = ''delivered'' ORDER BY delivery_id;',
       '["Compare the ::date casts of both timestamps","A boolean expression can be selected directly"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 58
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'same-day-deliveries');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'rider-cod-vs-prepaid', 'Rider Workload: COD vs Prepaid', 'code', 'Hard', 'Logistics',
       'Conditional Aggregation', ARRAY['case-when']::text[], 'Cash handling is risk. Per rider (delivered runs only), return `name`, `cod_deliveries`, and `prepaid_deliveries` in one row each, most COD first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT r.name,
       SUM(CASE WHEN p.cod_amount > 0 THEN 1 ELSE 0 END) AS cod_deliveries,
       SUM(CASE WHEN p.cod_amount = 0 THEN 1 ELSE 0 END) AS prepaid_deliveries
FROM riders r
JOIN deliveries d ON d.rider_id = r.rider_id
JOIN parcels p ON p.parcel_id = d.parcel_id
WHERE d.status = ''delivered''
GROUP BY r.name ORDER BY cod_deliveries DESC;',
       '["Two conditional counts in one GROUP BY","COD-ness lives on the parcel"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 40
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'rider-cod-vs-prepaid');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'fastest-delivery-per-hub', 'Fastest Delivery per Hub', 'code', 'Hard', 'Logistics',
       'Window Functions', ARRAY['row-number','extract']::text[], 'Bragging rights: each hub''s single fastest delivered run. Return hub `city`, rider `name`, and `minutes` (pickup to delivery, whole minutes), fastest overall first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT city, name, minutes FROM (
  SELECT h.city, r.name,
         ROUND(EXTRACT(EPOCH FROM (d.delivered_at - d.picked_at)) / 60) AS minutes,
         ROW_NUMBER() OVER (PARTITION BY h.hub_id ORDER BY d.delivered_at - d.picked_at) AS rn
  FROM hubs h
  JOIN riders r ON r.hub_id = h.hub_id
  JOIN deliveries d ON d.rider_id = r.rider_id
  WHERE d.status = ''delivered''
) t WHERE rn = 1 ORDER BY minutes;',
       '["Duration = delivered_at - picked_at","ROW_NUMBER per hub ordered by duration ascending","EPOCH/60 for minutes"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 33
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'fastest-delivery-per-hub');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-timestamp-date-cast', 'Casting a Timestamp to a Date', 'mcq', 'Easy', 'Logistics',
       'Date Functions', ARRAY['cast']::text[], '`picked_at` is `2026-06-01 10:00:00`.

What does `picked_at::date` give you in Postgres?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"2026-06-01 — the date part only"},{"label":"B","text":"10:00:00 — the time part only"},{"label":"C","text":"An error; timestamps can''t be cast"},{"label":"D","text":"The Unix epoch seconds"}]'::jsonb, 'A',
       NULL, 0, NULL, 82
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-timestamp-date-cast');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-interval-subtraction', 'Subtracting Two Timestamps', 'mcq', 'Medium', 'Logistics',
       'Date Functions', ARRAY['interval']::text[], 'In Postgres, `delivered_at - picked_at` (both timestamps) returns which type?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"An integer number of seconds"},{"label":"B","text":"An INTERVAL (e.g. ''05:30:00'')"},{"label":"C","text":"A float number of days"},{"label":"D","text":"A new timestamp"}]'::jsonb, 'B',
       NULL, 0, NULL, 56
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-interval-subtraction');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-multiple-attempts-grain', 'Choosing the Right Grain', 'mcq', 'Medium', 'Logistics',
       'Modeling', ARRAY['concept','grain']::text[], '`deliveries` holds one row **per attempt**, and a parcel can have several attempts.

To report "parcels delivered per rider", what must you be careful about?',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), '',
       '[]'::jsonb, '[{"label":"A","text":"Nothing — COUNT(*) on deliveries is always the parcel count"},{"label":"B","text":"Failed attempts exist, so count only rows with status=''delivered'' (and distinct parcels if needed)"},{"label":"C","text":"You must join hubs first"},{"label":"D","text":"COUNT(DISTINCT rider_id) is required"}]'::jsonb, 'B',
       NULL, 0, NULL, 61
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-multiple-attempts-grain');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'failed-first-attempt-cost', 'Case: The Cost of Failed First Attempts', 'case_study', 'Hard', 'Logistics',
       'Window Functions', ARRAY['lag','attempts']::text[], '**Scenario.** Every failed first attempt means a re-dispatch. Ops wants the parcels whose **first attempt failed**, and whether a later attempt rescued them.

Return `parcel_id`, first attempt''s `status` (`first_status`), and `rescued` (true if any later attempt delivered).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'WITH ranked AS (
  SELECT parcel_id, status,
         ROW_NUMBER() OVER (PARTITION BY parcel_id ORDER BY picked_at) AS attempt_no
  FROM deliveries
)
SELECT f.parcel_id, f.status AS first_status,
       EXISTS (
         SELECT 1 FROM ranked l
         WHERE l.parcel_id = f.parcel_id AND l.attempt_no > 1 AND l.status = ''delivered''
       ) AS rescued
FROM ranked f
WHERE f.attempt_no = 1 AND f.status = ''failed'';',
       '["Number attempts per parcel with ROW_NUMBER over picked_at","First attempt = attempt_no 1","EXISTS over later attempts answers ''rescued''"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 28
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'failed-first-attempt-cost');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mission-sla-crunch', 'Mission: SLA Crunch Week', 'root', 'Medium', 'Logistics',
       'Investigation', ARRAY['mission','sla']::text[], '**The story.** A key e-commerce client threatens to switch couriers: "your Dhaka deliveries are slipping." The city lead gives you the ops database and 48 hours. Four steps from raw counts to the exact riders and runs behind the slippage.',
       '', '', '',
       '[]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 46
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mission-sla-crunch');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'premium-plan-roster', 'Premium Plan Roster', 'code', 'Easy', 'Telco',
       'Joins', ARRAY['join','where']::text[], 'Return `name` and `activated_on` of subscribers on plans costing **৳500+ per month**, newest activation first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, s.activated_on
FROM subscribers s JOIN plans p ON p.plan_id = s.plan_id
WHERE p.monthly_fee >= 500 ORDER BY s.activated_on DESC;',
       '["Fee filter lives on plans","Join then WHERE"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 82
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'premium-plan-roster');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'small-recharges', 'Micro-Recharge Behaviour', 'code', 'Easy', 'Telco',
       'Filtering', ARRAY['where','count']::text[], 'Micro top-ups (< ৳150) signal price sensitivity. Return one row with their count (`micro_count`) and total value (`micro_value`).',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT COUNT(*) AS micro_count, SUM(amount) AS micro_value FROM recharges WHERE amount < 150;',
       '["Aggregate over a filtered set — no GROUP BY needed","COUNT(*) and SUM(amount) in one SELECT"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 83
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'small-recharges');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'district-subscriber-mix', 'Subscriber Mix by District', 'code', 'Medium', 'Telco',
       'Aggregation', ARRAY['group-by','count-distinct']::text[], 'Regional planning: per `district`, return subscriber count (`subs`) and how many **distinct plans** are in use there (`plans_used`), most subs first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT district, COUNT(*) AS subs, COUNT(DISTINCT plan_id) AS plans_used
FROM subscribers GROUP BY district ORDER BY subs DESC;',
       '["COUNT(DISTINCT plan_id) inside the same GROUP BY","Plain COUNT(*) gives the subscriber count"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 65
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'district-subscriber-mix');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'voice-heavy-users', 'Voice-Heavy Subscribers', 'code', 'Medium', 'Telco',
       'Aggregation', ARRAY['having','sum']::text[], 'Voice bundles are due an upsell. Return `name` and total voice minutes (`total_min`) of subscribers with **more than 100 minutes** across the recorded days, highest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, SUM(u.voice_min) AS total_min
FROM subscribers s JOIN usage_daily u ON u.sub_id = s.sub_id
GROUP BY s.name HAVING SUM(u.voice_min) > 100
ORDER BY total_min DESC;',
       '["SUM voice_min per subscriber","The >100 test goes in HAVING"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 62
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'voice-heavy-users');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'data-vs-plan-allowance', 'Usage vs Plan Allowance', 'code', 'Hard', 'Telco',
       'Joins', ARRAY['ratio','multi-join']::text[], 'Who''s outgrowing their plan? Per subscriber, compare recorded total data (GB) to the plan''s monthly allowance. Return `name`, plan `allowance_gb`, `used_gb` (2 decimals), and `pct_of_allowance` (1 decimal), highest percentage first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, p.data_gb AS allowance_gb,
       ROUND(SUM(u.data_mb) / 1024.0, 2) AS used_gb,
       ROUND(100.0 * SUM(u.data_mb) / 1024.0 / p.data_gb, 1) AS pct_of_allowance
FROM subscribers s
JOIN plans p ON p.plan_id = s.plan_id
JOIN usage_daily u ON u.sub_id = s.sub_id
GROUP BY s.name, p.data_gb
ORDER BY pct_of_allowance DESC;',
       '["GB = SUM(data_mb)/1024.0","Percentage against p.data_gb","Group by subscriber and allowance"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 38
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'data-vs-plan-allowance');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'second-highest-recharge', 'Second-Highest Recharge', 'code', 'Hard', 'Telco',
       'Window Functions', ARRAY['dense-rank','offset']::text[], 'A classic interview twist: find the **second-highest distinct** recharge amount, and every recharge at that amount. Return `recharge_id`, `sub_id`, and `amount`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT recharge_id, sub_id, amount FROM (
  SELECT recharge_id, sub_id, amount, DENSE_RANK() OVER (ORDER BY amount DESC) AS dr
  FROM recharges
) t WHERE dr = 2;',
       '["DENSE_RANK handles ties on the top amount","Keep dr = 2"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, 1800, 41
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'second-highest-recharge');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-composite-pk', 'Why a Composite Primary Key?', 'mcq', 'Medium', 'Telco',
       'Modeling', ARRAY['concept','keys']::text[], '`usage_daily` declares `PRIMARY KEY (sub_id, usage_date)`.

What does that model?',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), '',
       '[]'::jsonb, '[{"label":"A","text":"Each subscriber may appear at most once per day — one usage row per subscriber-day"},{"label":"B","text":"sub_id alone must be unique"},{"label":"C","text":"usage_date alone must be unique"},{"label":"D","text":"The table can''t have foreign keys"}]'::jsonb, 'A',
       NULL, 0, NULL, 67
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-composite-pk');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mcq-dense-vs-rank', 'RANK vs DENSE_RANK on Ties', 'mcq', 'Medium', 'Telco',
       'Window Functions', ARRAY['concept','rank']::text[], 'Recharge amounts 999, 599, 599, 349 are ranked descending.

What ranks do RANK() and DENSE_RANK() give the ৳349 row?',
       '', '', '',
       '[]'::jsonb, '[{"label":"A","text":"RANK: 4, DENSE_RANK: 3 — RANK skips after ties, DENSE_RANK doesn''t"},{"label":"B","text":"Both give 4"},{"label":"C","text":"Both give 3"},{"label":"D","text":"RANK: 3, DENSE_RANK: 4"}]'::jsonb, 'A',
       NULL, 0, NULL, 54
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mcq-dense-vs-rank');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'arpu-by-plan', 'Case: ARPU by Plan', 'case_study', 'Medium', 'Telco',
       'Joins', ARRAY['arpu','avg']::text[], '**Scenario.** The pricing committee reviews ARPU (average recharge revenue per user) plan by plan before the next tariff filing.

Per plan, return `name`, subscriber count (`subs`), total recharge revenue (`revenue`), and `arpu` (revenue ÷ subs, 2 decimals), highest ARPU first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT p.name, COUNT(DISTINCT s.sub_id) AS subs,
       COALESCE(SUM(r.amount), 0) AS revenue,
       ROUND(COALESCE(SUM(r.amount), 0) / COUNT(DISTINCT s.sub_id), 2) AS arpu
FROM plans p
JOIN subscribers s ON s.plan_id = p.plan_id
LEFT JOIN recharges r ON r.sub_id = s.sub_id
GROUP BY p.name ORDER BY arpu DESC;',
       '["COUNT(DISTINCT sub_id) — recharges duplicate subscriber rows","LEFT JOIN keeps plans whose subs never recharged","ARPU = revenue / subs"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 42
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'arpu-by-plan');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'inactive-data-users', 'Case: Paying but Barely Using', 'case_study', 'Medium', 'Telco',
       'Subqueries', ARRAY['avg','comparison']::text[], '**Scenario.** Retention suspects some subscribers pay for data they never use — prime downgrade-offer targets.

Return `name` and `avg_daily_mb` (average daily data, 1 decimal) of subscribers whose average is **below the overall average** across all subscriber-days, lowest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, ROUND(AVG(u.data_mb), 1) AS avg_daily_mb
FROM subscribers s JOIN usage_daily u ON u.sub_id = s.sub_id
GROUP BY s.name
HAVING AVG(u.data_mb) < (SELECT AVG(data_mb) FROM usage_daily)
ORDER BY avg_daily_mb;',
       '["Overall average via a scalar subquery","Compare per-subscriber AVG in HAVING"]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 45
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'inactive-data-users');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'mission-congestion-hunt', 'Mission: The Congestion Hunt', 'root', 'Medium', 'Telco',
       'Investigation', ARRAY['mission','network']::text[], '**The story.** Complaint tickets about slow data tripled this week. The network team swears the towers are fine; your CTO wants proof from the usage data. Four steps: from raw consumption to naming exactly which subscribers and days drove the spike.',
       '', '', '',
       '[]'::jsonb, '[]'::jsonb, NULL,
       NULL, 0, NULL, 47
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'mission-congestion-hunt');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'collections-1-book-overview', 'Step 1: Size the Book', 'code', 'Easy', 'Fintech',
       'Aggregation', ARRAY['group-by']::text[], 'First, the shape of the book by geography: return `district`, number of loans (`loans`), and total `principal` disbursed (`disbursed`), largest book first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT district, COUNT(*) AS loans, SUM(principal) AS disbursed
FROM loans GROUP BY district ORDER BY disbursed DESC;',
       '["GROUP BY district","COUNT and SUM together"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-collections-sprint'), 0, NULL, 78
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'collections-1-book-overview');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'collections-2-recovery-rate', 'Step 2: Recovery Rate per District', 'code', 'Medium', 'Fintech',
       'Joins', ARRAY['left-join','ratio']::text[], 'Now the health metric: per district, how much of the disbursed principal has come back? Return `district`, `disbursed`, `recovered`, and `recovery_pct` (1 decimal), lowest recovery first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT l.district, SUM(DISTINCT_PRINCIPAL.principal) AS disbursed,
       COALESCE(SUM(r.amount), 0) AS recovered,
       ROUND(100.0 * COALESCE(SUM(r.amount), 0) / SUM(DISTINCT_PRINCIPAL.principal), 1) AS recovery_pct
FROM loans l
JOIN LATERAL (SELECT l.principal) DISTINCT_PRINCIPAL ON true
LEFT JOIN repayments r ON r.loan_id = l.loan_id
GROUP BY l.district
ORDER BY recovery_pct;',
       '["Careful: joining repayments duplicates loan rows — aggregate repayments per loan first, or sum principal separately","A subquery per loan (or CTE) avoids double-counting principal","Recovery = repaid / disbursed"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-collections-sprint'), 1, NULL, 38
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'collections-2-recovery-rate');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'collections-3-slow-payers', 'Step 3: The Slow Payers', 'code', 'Medium', 'Fintech',
       'Aggregation', ARRAY['having','date']::text[], 'District view done — now names. Active loans whose **last repayment** was before 1 May 2026 are officially slow. Return `loan_id`, `borrower`, and `last_paid`, oldest last payment first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'SELECT l.loan_id, l.borrower, MAX(r.paid_on) AS last_paid
FROM loans l JOIN repayments r ON r.loan_id = l.loan_id
WHERE l.status = ''active''
GROUP BY l.loan_id, l.borrower
HAVING MAX(r.paid_on) < ''2026-05-01''
ORDER BY last_paid;',
       '["MAX(paid_on) per loan is the last payment","The cutoff test on an aggregate goes in HAVING"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-collections-sprint'), 2, NULL, 51
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'collections-3-slow-payers');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'collections-4-call-list', 'Step 4: The Call List', 'code', 'Hard', 'Fintech',
       'Subqueries', ARRAY['cte','outstanding']::text[], 'Final deliverable: the ranked call list. For every **non-paid** loan, compute outstanding (principal − repaid) and rank by outstanding descending. Return `rank`, `borrower`, `district`, `status`, and `outstanding`.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'fintech_microloan'), ''), 'WITH repaid AS (
  SELECT loan_id, SUM(amount) AS total FROM repayments GROUP BY loan_id
)
SELECT RANK() OVER (ORDER BY l.principal - COALESCE(rp.total, 0) DESC) AS rank,
       l.borrower, l.district, l.status,
       l.principal - COALESCE(rp.total, 0) AS outstanding
FROM loans l LEFT JOIN repaid rp ON rp.loan_id = l.loan_id
WHERE l.status <> ''paid''
ORDER BY outstanding DESC;',
       '["A CTE of repayments per loan keeps the main query clean","RANK() OVER (ORDER BY outstanding DESC)","COALESCE for never-paid loans"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-collections-sprint'), 3, 1800, 29
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'collections-4-call-list');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'sla-1-attempt-outcomes', 'Step 1: Attempt Outcomes', 'code', 'Easy', 'Logistics',
       'Aggregation', ARRAY['group-by']::text[], 'Baseline first: return each delivery `status` and its attempt count (`attempts`), largest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT status, COUNT(*) AS attempts FROM deliveries GROUP BY status ORDER BY attempts DESC;',
       '["GROUP BY status over the attempts table","ORDER BY the count descending"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-sla-crunch'), 0, NULL, 85
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'sla-1-attempt-outcomes');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'sla-2-duration-distribution', 'Step 2: How Long Deliveries Take', 'code', 'Medium', 'Logistics',
       'Date Functions', ARRAY['extract','bucketing']::text[], 'The SLA is 6 hours. Bucket **delivered** runs into `''within_sla''` (≤ 6h) and `''breached''` (> 6h). Return `bucket` and `runs`, breaches first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT CASE WHEN EXTRACT(EPOCH FROM (delivered_at - picked_at)) / 3600 <= 6
            THEN ''within_sla'' ELSE ''breached'' END AS bucket,
       COUNT(*) AS runs
FROM deliveries WHERE status = ''delivered''
GROUP BY 1 ORDER BY bucket;',
       '["Hours = EPOCH difference / 3600","CASE builds the bucket label","GROUP BY 1 groups by the first select expression"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-sla-crunch'), 1, NULL, 49
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'sla-2-duration-distribution');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'sla-3-rider-breach-rate', 'Step 3: Breaches by Rider', 'code', 'Medium', 'Logistics',
       'Conditional Aggregation', ARRAY['case-when','ratio']::text[], 'Now names: per rider (delivered runs), return `name`, `total_runs`, `breaches` (> 6h), most breaches first, ties by name.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT r.name, COUNT(*) AS total_runs,
       SUM(CASE WHEN EXTRACT(EPOCH FROM (d.delivered_at - d.picked_at)) / 3600 > 6 THEN 1 ELSE 0 END) AS breaches
FROM riders r JOIN deliveries d ON d.rider_id = r.rider_id
WHERE d.status = ''delivered''
GROUP BY r.name ORDER BY breaches DESC, name;',
       '["Reuse the 6-hour test inside a conditional SUM","Count total and breaches in the same pass"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-sla-crunch'), 2, NULL, 47
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'sla-3-rider-breach-rate');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'sla-4-worst-runs-report', 'Step 4: The Evidence Pack', 'code', 'Hard', 'Logistics',
       'Window Functions', ARRAY['rank','report']::text[], 'For the client call, rank the 5 slowest delivered runs. Return `rank`, parcel `parcel_id`, rider `name`, `hours` (1 decimal), slowest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'logistics_courier'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'logistics_courier'), ''), 'SELECT RANK() OVER (ORDER BY d.delivered_at - d.picked_at DESC) AS rank,
       d.parcel_id, r.name,
       ROUND((EXTRACT(EPOCH FROM (d.delivered_at - d.picked_at)) / 3600)::numeric, 1) AS hours
FROM deliveries d JOIN riders r ON r.rider_id = d.rider_id
WHERE d.status = ''delivered''
ORDER BY hours DESC LIMIT 5;',
       '["RANK over the duration descending","LIMIT 5 after ordering","Round hours to 1 decimal"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-sla-crunch'), 3, 1800, 36
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'sla-4-worst-runs-report');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'congestion-1-daily-network-load', 'Step 1: Daily Network Load', 'code', 'Easy', 'Telco',
       'Aggregation', ARRAY['group-by','sum']::text[], 'Start with the macro picture: total data consumed per `usage_date` (`total_mb`), in date order.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT usage_date, SUM(data_mb) AS total_mb FROM usage_daily GROUP BY usage_date ORDER BY usage_date;',
       '["GROUP BY the date, SUM the megabytes","Chronological order = ORDER BY usage_date"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-congestion-hunt'), 0, NULL, 86
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'congestion-1-daily-network-load');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'congestion-2-district-load', 'Step 2: Where the Load Lives', 'code', 'Medium', 'Telco',
       'Joins', ARRAY['join','group-by']::text[], 'The towers are regional — so is the truth. Return `district` and total data (`total_mb`), heaviest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.district, SUM(u.data_mb) AS total_mb
FROM subscribers s JOIN usage_daily u ON u.sub_id = s.sub_id
GROUP BY s.district ORDER BY total_mb DESC;',
       '["District comes from subscribers","Join then aggregate"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-congestion-hunt'), 1, NULL, 68
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'congestion-2-district-load');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'congestion-3-heavy-hitters', 'Step 3: The Heavy Hitters', 'code', 'Medium', 'Telco',
       'Window Functions', ARRAY['window','share']::text[], 'Concentration check: per subscriber, total data and their **share of the whole network''s** data (`pct_of_network`, 1 decimal), biggest first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT s.name, SUM(u.data_mb) AS total_mb,
       ROUND(100.0 * SUM(u.data_mb) / SUM(SUM(u.data_mb)) OVER (), 1) AS pct_of_network
FROM subscribers s JOIN usage_daily u ON u.sub_id = s.sub_id
GROUP BY s.name ORDER BY total_mb DESC;',
       '["SUM(SUM(...)) OVER () = grand total beside each group","Share = 100.0 * subscriber / network"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-congestion-hunt'), 2, NULL, 44
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'congestion-3-heavy-hitters');

INSERT INTO public.careerprep_questions
  (slug, title, question_type, difficulty, industry, category, tags, content_md,
   schema_sql, initial_sql, solution_sql, hints, options, correct_option,
   parent_id, order_index, time_limit_secs, success_rate)
SELECT 'congestion-4-spike-days', 'Step 4: Naming the Spike', 'code', 'Hard', 'Telco',
       'Window Functions', ARRAY['avg-over','anomaly']::text[], 'The proof: subscriber-days that ran **at least 1.3×** that subscriber''s own average. Return `name`, `usage_date`, `data_mb`, and their personal average (`avg_mb`, 1 decimal), biggest overshoot first.',
       COALESCE((SELECT schema_sql FROM _worlds WHERE name = 'telco_network'), ''), COALESCE((SELECT initial_sql FROM _worlds WHERE name = 'telco_network'), ''), 'SELECT name, usage_date, data_mb, avg_mb FROM (
  SELECT s.name, u.usage_date, u.data_mb,
         ROUND(AVG(u.data_mb) OVER (PARTITION BY u.sub_id), 1) AS avg_mb
  FROM subscribers s JOIN usage_daily u ON u.sub_id = s.sub_id
) t WHERE data_mb >= 1.3 * avg_mb
ORDER BY data_mb / avg_mb DESC;',
       '["AVG(...) OVER (PARTITION BY subscriber) puts the personal average on every row","Filter rows ≥ 1.5× that average in an outer query"]'::jsonb, '[]'::jsonb, NULL,
       (SELECT id FROM public.careerprep_questions WHERE slug = 'mission-congestion-hunt'), 3, 1800, 30
WHERE NOT EXISTS (SELECT 1 FROM public.careerprep_questions WHERE slug = 'congestion-4-spike-days');

DROP TABLE _worlds;
