// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llmeentlxjauihrkkrjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsbWVlbnRseGphdWlocmtrcmpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzg1NTMsImV4cCI6MjA2ODc1NDU1M30.xOrWNt9jkPhI11CFkkFTgFjuH8SNbIjp4oyk3e34vt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});